### ISSUE TITLE
Option "save domain only" not working

### ISSUE THREAD

**Issue by gander** [keepassxreboot/keepassxc-browser#1044]
## Expected Behavior
Only the domain should be saved

## Current Behavior
Not only the domain but the entire url is saved

## Steps to Reproduce
1. I set in configuration `save domain only` checked
2. On any page, I enter my login details in the form
3. I click send
4. A menu for adding a new entry to KeePass appears at the top
5. I click the green button for adding a new entry
6. A new entry appears in KeePass:
- Title: `example.com`
- Username: `gander`
- Password: `*****`
- URL: `https://example.com/account/register`

## Debug info
KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Win32
Browser: Chrome/Chromium 86.0.4240.75

**Comment by varjolintu** [comment]
Could not reproduce.

**Comment by gander** [comment]
I'll try to record the event

**Comment by solson** [comment]
In my testing, "save domain only" *does* work if I right-click and go to `KeePassXC-Browser > Save credentials` manually, but if I first submit the login and then click `New` in the banner after redirecting, then it inserts the full URL instead of just the domain.

This is one example page where I reproduced the problem: https://backloggery.com/login.php

<details><summary>Versions</summary>

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 81.0

</details>
