### ISSUE TITLE
Multiple auth dropdown menu and fields with custom focus event handling 

### ISSUE THREAD

**Issue by d-faure** [keepassxreboot/keepassxc-browser#1055]
Nowdays, there seems to get some kind of fashion for event-enhanced fields in login forms, with the field description label moving from inside the field itself when not focused (like a placeholder) to somewhere around / below / above as soon as focused.

## Expected Behavior
When several auth records are available for the same site the extension generates a dropdown menu to let select the desired record to use, either below the active field or in the extension icon's menu.

## Current Behavior
As soon as an entry is selected in the extension-driven dropdown menu, the related mouse event seems to be handled as a focus-out event by the login field and the auth record data aren't taken in account.
More annoyingly, as soon as the extension's icon menu providing the same kind of auth record enumeration is opened or the right-click menu entry extension's functions are used a focus-out event is triggered and the field isn't filled.

## Possible Solution
Provide a way to select (and inject) auth data without changing focus state

## Steps to Reproduce (for bugs)
Try to auth on related sites, such as:
https://particulier.edf.fr/
but most of the site having such focus sensible fields are problematic

## Debug info

KeePassXC - v2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Win
Browser: Chrome+Firefox

**Comment by varjolintu** [comment]
You mean the login field at the separate login page under https://espace-client.edf.fr/ ? I had no problems with it after I put the URL to Site Preferences and enabled Username-only Detection for it.

I couldn't reproduce the behavior you described, and I didn't actually fully understood it. But maybe the fix for https://github.com/keepassxreboot/keepassxc-browser/issues/1053 will solve your problems.
