### ISSUE TITLE
No connected database was found.

### ISSUE THREAD

**Issue by h2ofranck** [keepassxreboot/keepassxc-browser#1062]
hello,
"No connected database was found."

## Debug info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-52-generic

Enabled extensions:
- Auto-Type
- Intégration aux navigateurs
- Agent SSH
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64
Browser: Microsoft Edge 88.0.673.0

**Comment by varjolintu** [comment]
Could you elaborate this a bit more?

**Comment by h2ofranck** [comment]
Yes of course, excuse me. And sorry for my English.
I cannot connect to the keepass database.
I have the message (translated from French):

> An error has occurred in KeePassXC-Browser:
> Unable to connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings._


![2020-10-23-16h43](https://user-images.githubusercontent.com/11783920/97018240-358d8980-154f-11eb-9390-0505b23ad23f.png)
![2020-10-23-16h41](https://user-images.githubusercontent.com/11783920/97018239-358d8980-154f-11eb-8877-eb979d5c0aae.png)
![2020-10-23-16h37](https://user-images.githubusercontent.com/11783920/97018249-36beb680-154f-11eb-9e3c-61a2b4a82ea4.png)

**Comment by varjolintu** [comment]
Please check the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by h2ofranck** [comment]
thanks, but I did not understand what to do in the documentation. It does not work.

**Comment by varjolintu** [comment]
Oh sorry. I just noticed you are using the new Edge with Linux. You can use the Custom Browser feature for this, but it requires the latest KeePassXC, or at least 2.6.0.

But because you are using older version, you'll have to copy the [Chromium's Native Messaging script file](https://github.com/keepassxreboot/keepassxc-browser/wiki/Native-messaging-script-files) manually to Edge's configuration path, which I don't know what it is (yet). It's probably something like `~/.config/microsoftedge-develop/NativeMessagingHosts`.

**Comment by h2ofranck** [comment]
yes!
i updated keepassxc to 2.6.2, and configured manually, it works.
Big thanks.

this path is: .config/microsoft-edge-dev/NativeMessagingHosts/
