### ISSUE TITLE
Icon momentarily goes green when refreshing or navigation to a page, with locked database.

### ISSUE THREAD

**Issue by 7415963987456321** [keepassxreboot/keepassxc-browser#1106]
## Expected Behavior
The key icon in the browser should show the lock icon when the database is locked. And only the green icon when the database is open.

## Current Behavior
When navigating to a page with the browser or refreshing the current one, the key icon will momentarily turn green indicating an unlocked database when in fact it is locked. 

## Possible Solution
Haven't really had time to dig into the code. 

## Steps to Reproduce (for bugs)
1. Have KeypassXC database locked and this extension installed.
2. Navigate to a page in browser or refresh
3. Observe the icon flashing green, and then to locked.

## Debug info
KeePassXC - 2.6.2.
KeePassXC-Browser - 1.7.3
OS: Linux
Browser: Firefox 81.0.2 (64-bit)

**Comment by normanr** [comment]
You don't specify which icon, I assume you mean the one on the toolbar, and not the one that gets placed on the webpage? My guess is that the first green icon is just a default (before the extension has figured out what its state is). Maybe there should be a different icon used at that point?

**Comment by WhyNotHugo** [comment]
Also happens each time a new tab is opened.

> My guess is that the first green icon is just a default (before the extension has figured out what its state is).

The icon doesn't need to reset to default when a page changes tho. It's not like add-ons all restart on tab change; they maintain a continuous state.

**Comment by WhyNotHugo** [comment]
Right, so I've looked through the code, and the issue comes from the fact that [`browserAction.setIcon()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setIcon) is called with a [`tabId`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setIcon#tabid)(this field is optional).

This sets the icon **only** for the current tab, so when switching tabs, the "global" icon is shown until a new per-tab icon is calculated.

`tabId` is optional, and in case of a locked DB, it should be unset so that the icon changes for **all** tabs.

**Comment by varjolintu** [comment]
@WhyNotHugo Thanks. I'll check out if this is a good place for a solution.
