### ISSUE TITLE
abendblatt.de: login fields (username/password) not detected 

### ISSUE THREAD

**Issue by cryptosteve2** [keepassxreboot/keepassxc-browser#1157]
The browser extension fails to detect the login fields (username & password) on https://www.abendblatt.de. Neither "Redetect login fields" nor "Choose custom login fields" works.

## Expected Behavior
Login fields should be detected and filled out properly on request. At least saving the credentials manually should work.

## Current Behavior
I can't save username/password for the site. I tried both "Redetect login fields" and "Choose custom login fields", but neither worked.

## Possible Solution
I have no idea, sorry.

## Steps to Reproduce (for bugs)

1. Go to https://www.abendblatt.de
2. Click on "Anmelden" (on the left of the headline/site-logo) and try to save username/password

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: MacOS Big Sur 11.1
Browser: Firefox 84.0 (64bit)

**Comment by varjolintu** [comment]
I can fill the credentials normally if I use the source of the iframe, which is `https://buy.tinypass.com/`, not `abendblatt.de`. If I go to the login page directly, the Credential Banner appears but for some reason it doesn't show on the main page, so that's clearly a bug. It should handle iframes too and show the Banner on the main page.

**Comment by almereyda** [comment]
This fits into the scope of #1358.

**Comment by varjolintu** [comment]
Showing the Credential Banner here is impossible because cross-origin frame access is blocked.
