### ISSUE TITLE
Support split databases/entries for passwords/OTP

### ISSUE THREAD

**Issue by Gunsmithy** [keepassxreboot/keepassxc-browser#1162]
In setting up TOTP with KeePassXC, I'm trying to follow the recommended practice of [keeping TOTP codes in a separate database.](https://keepassxc.org/docs/#faq-security-totp)  
When attempting to accomplish this with KeePassXC-Browser, I run into some issues when trying to auto-fill a username and password from one database and the TOTP code from another.

## Expected Behavior
Username and password fields should have the auto-fill button and search for entries for the domain as usual.  
TOTP field should have the auto-fill button that searches for entries for the domain that have TOTP setup, instead of auto-filling the TOTP with the previously selected entry.

## Current Behavior
Currently, clicking on the auto-fill button in the Username field of a website will show both entries from both databases as expected, the Password DB and the TOTP DB. (Ideally this would only show the one with username/password set.)  
Upon selecting the Password DB entry, the username and password is filled as expected.  
However, on selecting the auto-fill button in the TOTP field, nothing happens, as there is no TOTP setup for the Password DB entry.

## Possible Solution
It seems like the extension needs to be changed to display a list of accounts/use the only matching account when the OTP autofill button is clicked, instead of being locked into filling the TOTP code from the previously selected entry for the username/password auto-fill.  
A change to KeePassXC itself may also be necessary/ideal to be able to hide TOTP-only entries in a TOTP database from being auto-filled/displayed in the list of options for auto-filling username/passwords. This would allow one-click on both buttons to select the one entry from the Password and TOTP databases respectively, requiring no listing/least friction.

## Steps to Reproduce (for bugs)
1. Create/have a Discord account with 2FA enabled/OTP setup code ready for adding to KPXC
2. Open a 1st KPXC DB with an entry for URL discord.com containing username and password
3. Open a 2nd KPXC DB with an entry for URL discord.com containing a setup OTP code
4. Go to https://discord.com/login and select the auto-fill button on username (both entries should appear, ideally only the entry with the username/password would exist so no list would appear)
5. Select the 1st DB entry, username and password should be filled, click Login
6. Click the auto-fill button in 2FA field, nothing will happen, expected to automatically use the only entry with TOTP for discord.com
7. Workaround is to select the Chrome extension button again, choose the 2nd DB entry, then click the OTP auto-fill again

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: Windows 10 Pro v2004
Browser: Chrome Version 87.0.4280.88

**Comment by Gunsmithy** [comment]
![2021-01-06_15-55-24](https://user-images.githubusercontent.com/1775711/103819072-b7ae2a00-5037-11eb-9f73-83291d642de4.gif)

**Comment by varjolintu** [comment]
I have been actually thinking about this too. It's recommended that OTP's are stored in a separate database, so the extension should support this kind of scenario.

If there are multiple credentials and different OTP's setup for the same site, that is a little bit more difficult to handle.

Btw, many other sites has this kind of separate 2FA page too, and those are easier to test than Discord.

**Comment by Gunsmithy** [comment]
I agree, which is why I think the same listing behaviour should be used for the OTP auto-fill button as is used for the username/password.

It should also be noted by the way that specifying username or omitting it from the OTP DB has no effect. It seems to always attempt to use the TOTP from the Password DB.  

This same behaviour occurs on the Ubiquiti UniFi Controller website, as I'm sure does with many others as you suggest. Discord was the first popular-ish option I could think of. 😛

**Comment by droidmonkey** [comment]
I think showing the drop down to select an account when multiple exist at the totp prompt would be swell. This also helps if you have multiple accounts with multiple totp configured, you are sure to use the right one

**Comment by varjolintu** [comment]
@droidmonkey I'll do that. A lot of users have only one credentials for the site + TOTP credentials in another db so the default behavior could just be to use the first TOTP found in the set. If multiple TOTP codes are found, then show a list. It would work similar to the Username Field icon.

**Comment by varjolintu** [comment]
There's one requirement though: in the TOTP database entry must have a corresponding username (password is not needed). Otherwise there's no way to confirm which TOTP belongs to the selected entry.

**Comment by droidmonkey** [comment]
Can we show the entry title instead if there is no username? How do we handle password only entries in general?

**Comment by varjolintu** [comment]
Password-only entires show `- no username -` instead of the username. Password-only entires only fill the password, as expected.

**Comment by dancojocaru2000** [comment]
This doesn't seem to be working for me. I have both databases open yet the plugin says "Warning! No TOTP found.".

**Comment by varjolintu** [comment]
@dancojocaru2000 Could you provide some details on these entries in different databases?

**Comment by dancojocaru2000** [comment]
Same title, same username, same URL. In one database the entry also has the password, in the other database the entry also has TOTP set up.

**Comment by varjolintu** [comment]
> Same title, same username, same URL. In one database the entry also has the password, in the other database the entry also has TOTP set up.

Well, we ignore duplicate entries. It's enough if it's set up like this:
Database 1: Username, password, URL
Database 2, Matching username, matching URL, TOTP

**Comment by dancojocaru2000** [comment]
Perhaps I wasn't clear enough, but the TOTP database doesn't have the password saved in it.

**Comment by varjolintu** [comment]
> Perhaps I wasn't clear enough, but the TOTP database doesn't have the password saved in it.

And you have "Search in all opened databases for matching credentials" enabled in KeePassXC?

**Comment by dancojocaru2000** [comment]
...gosh, how could I miss that.

Yeah, sorry, I'm blind. It's a bit odd to me that I didn't see that option mentioned anywhere and it's not on by default.

Thanks!

**Comment by cBrenDev** [comment]
I can't figure out how to make this feature work.

I have two databases open, one called TOTP and one called Passwords.
Settings > Browser Integration > Search in all opened databases for matching credentials is enabled.
TOTP database has a single entry with Title, URL, Username, and TOTP
Passwords database has several entries, but importantly one matching entry with the same Title, URL, Username; no TOTP; password.

No matter what I do I cannot seem to get both entries to be combined into the one login attempt. I cannot seem to convince KeePassXC-Browser to connect to multiple databases simultaneously, which I assumed happened automatically when the search in all databases option is enabled. I also cannot force it manually - when clicking the "Connect" button in the Chrome Extension settings > Connected Databases, simply nothing happens if a database is already connected. I have successfully connected to each database independently.

Even using the right-click context menu to attempt to force particular values, no matter what I do I cannot access both password and TOTP with the same DB connection.

I can't find a user guide which covers this scenario at all so I really have no idea what I'm doing wrong or how to fix it.

I am on OSX 12.2.1 (Macbook Air, M1 2020) and Google Chrome 105.0.5195.125
Site: Segment.com (this has a three-step login; username-only; password-only; TOTP-only).

I've also learned through all of my testing that apparently credentials are queried at some point ahead of time? Which is to say - when I'm connected to just the Passwords DB with no TOTP configured for this entry, I can get to the one-time code screen. Then, if I set up the TOTP for that entry in the Passwords DB, it will not be available on that page as the extension has effectively cached the fact that there is no TOTP available. Simply refreshing the page and re-entering the password fixes this, but it seems strange that it wouldn't check in real-time when I request to fill the field.

**Comment by varjolintu** [comment]
@cBrenDev This sounds like a scenario where your second database is a copy of the first one, so they share the same Root Group UUID which is used for definining the identity of a database. Try going to Database Settings -> Browser Integration and generate a new Root Group UUID for your second database.

**Comment by cBrenDev** [comment]
@varjolintu Impressive catch, yes that was the case and refreshing the Root Group UUID did improve things, but it didn't solve them. (I also had to remove stored keys before the extension attempted to connect to the refreshed database, which then allowed both to be connected simultaneously, but I still couldn't get the system to fill the different values or show a dropdown to select from each of them, even though the browser access prompt indicated it found multiple. Perhaps this goes all the way down to the entry level? Since I copied the DB, pared it down to the one entry, then removed the password and added the OTP.)

Creating a brand-new DB and entry DID solve them, or at least made it possible to work. Is the expected behavior as I'm seeing it?
- Login fields detected, prompted to share access with one or more entries (I allow both)
- Username has no conflict, is fillable completely by autotype (ctrl-shift-u shortcut for example)
- Password has an apparent conflict between known-value and empty, so a dropdown appears which shows two apparently identical entries, and I need to manually select the one which actually holds the password. Shortcut ctrl-shift-i simply highlights an entry in the dropdown.
- TOTP just works, is autofilled as soon as I reach that screen

It seems like the dropdown does show the Group Names for each entry if they're different, so I can simply store all TOTP entries in a TOTP group and it should be easy enough to select the correct password-bearing entry from the dropdown, but just wanted to make sure that it was intended for the presence of an empty password to cause this extra step.

**Comment by varjolintu** [comment]
@cBrenDev Only username and URL should be identical for the separate TOTP entry in your second database. The password is not needed.

**Comment by cBrenDev** [comment]
@varjolintu I think that part is pretty clear - if password had to be the same, then there's no point in having a second database for TOTP.

What I'm saying is that the behavior I observe is that the two entries aren't really being "merged" in the way I expected, which might simply mean my expectations are wrong. I expected that by having the two databases open, the two entries would effectively be combined into one and auto fill would work across password and OTP with no manual intervention, but in practice I have to select the password-containing entry from a drop-down containing both the entry with TOTP only and the entry with password only.

**Comment by varjolintu** [comment]
@cBrenDev I'm taking a look at this because I also ran to some problems with a page where 2FA is on a second page after the login, and my TOTP is in a second database. This might be a scenario where the behavior is not tested properly, and the same case has caused headaches earlier too.

**Comment by varjolintu** [comment]
@cBrenDev I made one fix for the duplicate entry where the password is empty for the second one: https://github.com/keepassxreboot/keepassxc-browser/pull/1724. So far I didn't have problems filling the TOTP when testing this a little bit (I was using a Mastodon instance site where 2FA is on a second page).

**Comment by cBrenDev** [comment]
@varjolintu I saw that this made it to a release and am happy to report that it fixes my case as well :)
