### ISSUE TITLE
keepassxc-browser shows password after click "fill credential from KeePassXC"

### ISSUE THREAD

**Issue by nibexo** [keepassxreboot/keepassxc-browser#1187]
When I have saved in KeePassXC database login and pasword for https://portalpacjenta.luxmed.pl/PatientPortal/Account/LogOn
And I open this page
And I click icon "fill credential from KeePassXC"
Then login and password is filled but password is not as ***** like it is normally but showed like login. I attach print screen with fake data but it shows wrong behaviour. 
Additional information if I click "log in" page shows "Enter login and password", when I use on other page it works fine. 
![DeepinScreenshot_select-area_20210118194422](https://user-images.githubusercontent.com/10156955/104952849-977e5380-59c5-11eb-95e4-4324c09713a0.png)

## Steps to Reproduce (for bugs)

1. Create login and password for https://portalpacjenta.luxmed.pl/PatientPortal/Account/LogOn 
2. Open login page:  https://portalpacjenta.luxmed.pl/PatientPortal/Account/LogOn 
3. Click icon  "fill credential from KeePassXC"

## Debug info
KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 84.0

**Comment by varjolintu** [comment]
This happens because the page actually has two password fields. One is the real one and another one is hidden with `type=text`. There's an internal script that checks for triggered events and shows input fields depending on that. So the page thinks the password has not been properly entered.

I doubt there's anything we can do about it.
