### ISSUE TITLE
Does not work on the login windows Etsy website - https://www.etsy.com

### ISSUE THREAD

**Issue by MaxBMic** [keepassxreboot/keepassxc-browser#1236]
Hello,

## Issue ##

keepassxc-browser does not work on https://www.etsy.com
unable to login to his account using the extension
the login window closes automatically.

## Steps to Reproduce

1. Go on https://www.etsy.com
2. Click on login
3. Use keepassxc-browser 

## System infos ##

KeePassXC-Browser version : 1.7.6
Version de KeePassXC : 2.6.4
Operating system: Linux
Browser: Vivaldi

Thank you :)

**Comment by droidmonkey** [comment]
I used it on etsy earlier this week...

**Comment by droidmonkey** [comment]
OK this is more to do with the crappy site design then anything. When you click on the KPXC logo to fill credentials the site thinks you are clicking outside of the login popup which causes it to close. You have to right click the credential field then choose KeePassXC-Browser -> Fill Username and Password. You can also use the keyboard shortcut to fill username/password.

**Comment by MaxBMic** [comment]
Right click => KeePassXC-Browser or keyboard shortcut does not work also

But I also think that the connection on Etsy is shitty you're right

**Comment by droidmonkey** [comment]
I just tested both keyboard shortcut and right click menu and it worked

**Comment by varjolintu** [comment]
I know a few more sites that wants to close the dynamically created dialog right after fill. Gotta see if there's anything we can do.

**Comment by droidmonkey** [comment]
Probably nothing because the button is in shadow DOM and absolutely placed so it will never be part of the hierarchy of the window and a click on the button will register as "outside". I did notice that when you click the field you don't get the list of choices, that could be a compromise and add Etsy and others to the predefined sites list to show the login choices when clicking into the username field.

**Comment by varjolintu** [comment]
Now tracked in #1358.
