### ISSUE TITLE
TypeError: target.shadowSelectorAll is not a function

### ISSUE THREAD

**Issue by ximex** [keepassxreboot/keepassxc-browser#1352]
## Expected Behavior
No errors in the browser console

## Current Behavior
I got this error in the browser console: `TypeError: target.shadowSelectorAll is not a function`

## Steps to Reproduce (for bugs)
Couldn't reproduce it

## Debug info
KeePassXC - 2.6.5
KeePassXC-Browser - 1.7.8.1
Operating system: Kubuntu 21.04
Browser: Firefox

**Comment by varjolintu** [comment]
Hmm. Maybe it's used for an object that is not a HTML element.

**Comment by asd20752** [comment]
I have been experiencing this issue when dealing with ionic's custom components. 
![Skjermbilde 2021-07-14 233401](https://user-images.githubusercontent.com/11799746/125696111-dc1edc93-69eb-4dc5-bebd-15d6989b2b6a.png)

**Comment by varjolintu** [comment]
@asd20752 Do you have an example site this can be tested?

**Comment by asd20752** [comment]
I did not, but created a quick demo code which triggers the error. To me it seems it happens when elements are loaded after initial page creation. That is why in the example I have made it a modal so it will trigger after page initiation and rendering. 
http://keepass-shadow-error-demo.infinityfreeapp.com/
A Github repo with the code can also be found at https://github.com/asd20752/keepass-shadow-error-demo

**Comment by varjolintu** [comment]
Tested this a little bit and it only affects Firefox. A bit strange, but browser engines are.

**Comment by asd20752** [comment]
Now, I do not know what this function does, or what it's purpose is. But would it be as simple as changing the 
`if (target.shadowRoot)` to `if (target.shadowRoot && typeof target.shadowSelectorAll === "function")`

**Comment by varjolintu** [comment]
It's just a separate function for `querySelectorAll()` for objects in Shadow DOM. I'll test that fix. Thanks for the tip!
