### ISSUE TITLE
Not Working on Garmin Connect Website

### ISSUE THREAD

**Issue by faxotherapy** [keepassxreboot/keepassxc-browser#1366]
## Expected Behavior

Should work with Garming website, but unfortunately, web dev created an unnecessarily complicated login page. 

## Current Behavior

Not detecting fields in: https://connect.garmin.com/signin/

As shown on GIF image, I clicked on fields 1 and 2, but extension does not respond to my choice.

![Bug_on_Garmin](https://user-images.githubusercontent.com/6538008/125169970-878d4280-e1a4-11eb-84fb-23f06170ba42.gif)

## Possible Solution

Attemped to use “Choose custom login fields” option, but it's a complete mess. I can't even select the field.

## Steps to Reproduce (for bugs)

1. Create a dummy account on https://connect.garmin.com
2. Unfortunately, extension does not ask me to record/update KeepPass, as it should do.
3. Later re-connect to login page.
4. Extention does not detect the fields.
5. Using “Choose custom login fields” simply does not work.

## Debug info

KeePassXC - 2.6.6.
KeePassXC-Browser - 1.7.8.1
Operating system: MacOS Mojave
Browser: Firefox

**Comment by varjolintu** [comment]
Tracked in https://github.com/keepassxreboot/keepassxc-browser/issues/1358.

**Comment by diver864** [comment]
I just decided to try KeePassXC because of its UI and integrated browser plugin.  Excited, after many years of KeePass.   
Unfortunately, the second site I tried to use was:  https://connect.garmin.com.   I experienced the same as the OP.    

Only in the interest of supporting debugging, I can say that this combination of tools _does_ work on connect.garmin.com:  
 - KeePass (same database used by KeePassXC)
 - the Chrome extension 'Kee - Password Manager' (pointed at my KeePass database; not using the Kee db app); 
 - its dependency, KeePassPRC.plgx
 - Windows 10, Chromium Edge Version 91.0.864.67 (Official build) (64-bit)

I just tinker, I'm not a dev, so unfortunately cannot say why one works and the other does not...
The user experience with KeePassXC is better, and I hope this may help fix the issue.

**Comment by varjolintu** [comment]
@diver864 Change your entry URL to `https://sso.garmin.com` or `https://garmin.com`.

**Comment by andnorxor** [comment]
Thank you @varjolintu. `https://sso.garmin.com` worked for me.
If my assumption is correct, this is because the actual login form is an `<iframe>` with the `src` property set to `https://sso.garmin.com/sso/signin`, right? So next time I observe this behavior I'll just check the source code and apply the same workaround.

**Comment by varjolintu** [comment]
@andnorxor You are correct. If there's an iframe it's usually from another subdomain.
