### ISSUE TITLE
Provide shortcut to reload extension

### ISSUE THREAD

**Issue by Campano** [keepassxreboot/keepassxc-browser#1418]
This is a feature request.

Not much to say here, it's just such a routine operation, a shortcut would be more than welcome, it's annoying to have to go and click reload after opening a DB. A shortcut to launch the app from the browser would also be nice.

**Comment by varjolintu** [comment]
Launching the app won't probably work as good as it could. A reconnect feature already exists but it has some memory leaks that aren't solved yet.

**Comment by Campano** [comment]
@varjolintu I've reworded the title to narrow and clarify the request; lauching the app is really secondary.

The reconnect feature works well for me, but I would love to see a keyboard shortcut for it, as reconnecting is such a routine operation for me. Point & Click for this feels useless.

**Comment by varjolintu** [comment]
Keyboard shortcut can be added of course. It just needs to be configured manually by the user.

**Comment by smoyth** [comment]
Ok! Well here's hoping and begging!

The reason this would be so useful for me is that KeepassXC-browser sometimes just doesn't auto connect to KeepassXC even when it's unlocked. I'm not sure why and I'm sure it's complicated. But if I had a keyboard combo I could smash reflexively whenever I look over and the icon is greyed out instead of green, it would make the whole thing a lot smoother.

Thanks for a great extension!

**Comment by varjolintu** [comment]
It will be implemented for the next version :)

**Comment by Campano** [comment]
Can't find it in 1.7.11, how do I configure the shortcut?

**Comment by varjolintu** [comment]
@Campano Depends on your browser. The new shortcut is called "Reload". With Firefox you'll have to go to `about:addons`(the normal extension page), and then click the gear icon and choose _Manage Extension Shortcuts_ at the bottom. With Chromium based browsers you can just go to `chrome://extensions/shortcuts`.
