### ISSUE TITLE
Cannot autofill techdata's custom field

### ISSUE THREAD

**Issue by Zulgrib** [keepassxreboot/keepassxc-browser#1423]
## Expected Behavior
When setting up custom field in keepassxc-browser, it fills username, password and the custom field using "KPH: " prefixed custom attribute

## Current Behavior
When setting up custom field in keepassxc-browser, it fills username, password but the custom field using "KPH: " prefixed custom attribute is completely ignored.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)

1. Visit https://fr.techdata.com/
2. Clic «Connexion» (blue button)
3. Clic keepass icon to fill field
4. Second (username) and third (password) fields are filled, first field (custom) is not filled.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Linux x86_64
Browser: Chrome/Chromium 94.0.4606.71

`"defined-custom-fields":{"https://eauth.techdata.eu":{"fields":[["/html/body/div/div/div/form/div/div/input","INPUT text customerId numeric"]],"password":["/html/body/div/div/div/form/div/div[4]/input","INPUT password pf.pass alphanumeric"],"totp":null,"username":["/html/body/div/div/div/form/div/div[2]/input","INPUT text loginUserName alphanumeric"]}}`

No error in dev console following [these instructions](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#4-debug-the-extension-itself)

Note that I was not able to find anything else than a css and svg file in the dev console for the browser extension in the source tab for the webpage, and the background page has no "keepassxc-browser.js".

**Comment by varjolintu** [comment]
Still having the problem?

**Comment by roman-karpovich** [comment]
yes, problem still persists. i'm just not sure how to explicitly set custom field type, but can confirm - there are only default fields using "Choose custom login fields" options, i can just remap them.

**Comment by varjolintu** [comment]
@roman-karpovich You are not the one who created the ticket. Are you even using the same site?

**Comment by roman-karpovich** [comment]
correct. is it better to create copy of this ticket but for different site?

**Comment by varjolintu** [comment]
@roman-karpovich No need for copy if the issue is identical. But of course I'll need to know the different site as well.

**Comment by roman-karpovich** [comment]
Im trying to store account id for https://signin.aws.amazon.com/
When you log in as IAM user (not root), you have to specify which account you want to be logged in to, so in fact in case of aws login is the combination of three fields instead of regular two. So, I've created custom attribute with name `account id` and trying to use it with browser extension.

The problem is there is no custom fields available during choosing custom login fields even if they are being stored in entry.

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64
Browser: Chrome/Chromium 96.0.4664.93

**Comment by varjolintu** [comment]
@roman-karpovich To choose String Fields you must first select/skip Username, Password and TOTP selection. The instructions are on the screen.

**Comment by roman-karpovich** [comment]
i've already tried that and there is submit action right after TOTP. nothing similar to custom fields

**Comment by varjolintu** [comment]
You must select the String Fields before the Confirm.

**Comment by roman-karpovich** [comment]
Ohh. Sorry for being such stupid. Indeed, there is a selection of string fields.
There is just one strange point I've faced to. I've configured string field in fields selections for account id and it was not working (attribute still was not being autocompleted) before i renamed attribute from `account id` to `KPH: account id`. Now it's working for updated entries. 
It's totally fine for me, I'll just rename attributes inside other records. Just wondering - should it filter out non-prefixed attributes by design? Double-checked everything (documentation, github, plugin settings page) - no mentions of `KPH: ` prefix requirement except changelog (version 1.7.4).

**Comment by varjolintu** [comment]
@roman-karpovich All attributes that are visible for String Fields must be specified with `KPH: `.

**Comment by Zulgrib** [comment]
I do have a «KPH: 1 customerId» entry, was I supposed to name it another way ?

**Comment by Zulgrib** [comment]
Literally did not check the option to return advanced attributes beginning by «KPH: » in advanced browser integration settings.
Please update [FAQ](https://keepassxc.org/docs/#faq-browser-string-fields) to mention this is required.
