### ISSUE TITLE
KeePassXC + Brave both from Ubuntu Software - Browser Integration 'Cannot connect to KeePassXC'

### ISSUE THREAD

**Issue by LilWatson** [keepassxreboot/keepassxc-browser#1428]
After installing KeePassXC and Brave via Ubuntu Software i installed the XC Browser Extension and enabled the Brave Browser integration in XC.

## Expected Behavior
When i open KeePassXC and Brave, the Browser Extension should connect to KeePassXC.

## Current Behavior
'KeePassXC-Browser has encountered an error: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.'
After clicking 'reload' -> 'Key exchange was not successful.'

## Debug info

chrome-extension - report bugs info:
KeePassXC - unknown
KeePassXC-Browser - 1.7.9.1
Operating system: Linux x86_64
Browser: Chrome/Chromium 94.0.4606.81

actual KeePassXC Version: 2.4.3

![image](https://user-images.githubusercontent.com/77542969/137590801-459a2def-b8e5-4a25-a0b4-3c268973cadc.png)

I hope i'm not bothering you, im relatively new to linux and KeePassXC..

**Comment by droidmonkey** [comment]
You should use our AppImage or Snap instead since 2.4.3 is exceptionally outdated. https://keepassxc.org/download

Additionally, Brave tends to change its configuration storage location all the time on Linux, you may have to use the custom browser feature available on the newer versions of KeePassXC to select the appropriate native messaging settings folder.

Lastly, if Brave is installed as a snap this won't work no matter what you do.
