### ISSUE TITLE
Does not work with Librewolf

### ISSUE THREAD

**Issue by OrionRandD** [keepassxreboot/keepassxc-browser#1471]
Hi,
The add-on used to work with Librewolf,
But, since last update of browser and extension
they do not work any more and in Firefox it is not working either
:(

## Debug info
KeePassXC - unknown
KeePassXC-Browser - 1.7.10.1
Operating system: Linux x86_64
Browser: Librewolf 94.0 -> Mozilla Firefox 91.0

**Comment by varjolintu** [comment]
Go through the troubleshooting guide:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by Sean-OShea** [comment]
I have found a solution, this is a librewolf configuration issue i think. It's about the `org.keepassxc.keepassxc_browser.json` and where it should be located. I also have firefox installed so i already have that file at the right place for firefox (`~/.mozilla/native-messaging-hosts`) but librewolf needs that file too.

I'm on linux, using librewolf as an appimage. This means that i have a .librewolf folder in my Home directory. I just created the `native-messaging-hosts` directory inside it and changed the config location of firefox in the KeePassXC settings (in Tools>Settings>Browser Integration>Advanced

I'm switching from firefox to librewolf so this works for me, but there must be a better solution in order to make it work for both firefox and librewolf.

**Comment by varjolintu** [comment]
There is. The Custom Browser option you are already using. The script will be created automatically there if the option is used.

**Comment by Sean-OShea** [comment]
Indeed thanks for the precision, i just checked and both are now working together :)

**Comment by varjolintu** [comment]
@OrionRandD Please check the messages above if you are also using an AppImage. Thanks Sean!

**Comment by OrionRandD** [comment]
> @OrionRandD Please check the messages above if you are also using an AppImage. Thanks Sean!

Thx. I have solved that issue a while ago...

**Comment by DJCrashdummy** [comment]
@aegan123 i'm not sure if linking is a good idea, as you may run into some problems in the future not thinking about it...

i rather recommend the solution mentioned at 1) of the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) resp. perfectly summed up at https://github.com/keepassxreboot/keepassxc-browser/issues/2064#issuecomment-1874331946.

**Comment by DaanSelen** [comment]
```
ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
```

Will make it work!
