### ISSUE TITLE
Browser Extension: Custom string fields FAQ not working

### ISSUE THREAD

**Issue by LarsKumbier** [keepassxreboot/keepassxc-browser#1588]
## Overview
The example in the FAQ-entry "How do I fill in additional values on a webpage?" does not work, because the according keepassxc entry *must* have a username to be shown in the extension.

## Steps to Reproduce
Follow the FAQ entry (https://keepassxc.org/docs/#faq-string-fields):
> An example using the page https://meine.deutsche-bank.de/trxm/db/init.do
> Choose custom login fields for this page and select Branch, Account and Sub-account as String Fields when you reach step 4.
>    Go to your entry and add the following advanced attributes (the order is critical):
>    KPH: Branch
>    KPH: Account
>    KPH: Sub-account
> Test the filling of the string fields by refreshing the page and using the extension. 

Note: the password field is added, but the *username* is *not* chosen as field.

## Expected Behavior
When reloading the page and choosing "fill credentials" from the browser extensions' menu, I expect all fields to be filled.

## Actual Behavior
Nothing happens, because no username is given.

## Context
KeePassXC - 2.6.6
Firefox: 99.0beta6
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by orbanbalage** [comment]
Perhaps this is OT, but today I managed to get the String Fields working for https://app.revolut.com/start but the Extension behavior seems to only support filling for a single page – ie. in my case there is a String Field + username for the first login page which you submit, and then there is a subsequent page where the PIN has to be entered (the Extension detects this as four independent fields), which I also added as four additional String Fields. However the fill behavior will attempt to fill ALL the `KPH:  ` fields into the field on the first page, instead of filling only the first one.

**Comment by varjolintu** [comment]
@orbanbalage I can try to make this workflow a little better. In the meanwhile for these kind of cases I'd actually suggest that you fill the extra field from the context menu (using Fill Attribute). Then you don't have to use any Custom Login Fields.

**Comment by orbanbalage** [comment]
@varjolintu Thank you, actually currently I have the passcode set up in my password field, so in theory the Fill should work, but then this is a separate issue, because Filling does nothing, viz.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/285574/195317354-0d5ed401-7046-48db-bb86-299f88bb464f.png">

*correction* – the Auto-Type works however!

Thank you, this is a viable option then! :)

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc-browser/wiki/HowTo:-Special-Situations---Debugging.
