### ISSUE TITLE
Username Only option

### ISSUE THREAD

**Issue by phpsystems** [keepassxreboot/keepassxc-browser#159]
## Expected Behavior
On the right click, just as there is a password only option, a username only option would be nice. This is so sites (such as eventbrite) which only need my username at the first stage of login only get my username.

## Current Behavior
Only the option to submit the username and password exists. This means that the password has to be submitted, even if I only want to use my username.

## Possible Solution
Duplicate functionality based on the password only, and use a different field? Not really looked at code base so suggestion is probably unhelpful.

## Debug info

KeePassXC -2.3.3
keepassxc-browser - 1.1.3
Operating system: Win (10)
Browser: Chrome/Firefox/Vivaldi/Chromium
Proxy used: NO

**Comment by varjolintu** [comment]
Have you tried to use "Fill Username & Password" for these kind of situations?

**Comment by phpsystems** [comment]
Yes. As per current behaviour

**Comment by varjolintu** [comment]
The "Fill Username & Password" option should work too in these situations. It just doesn't even try to fill the password because no input field is found. I agree the name should be different when this kind of situation is detected.

**Comment by phpsystems** [comment]
And if the password field is actually hidden?

**Comment by varjolintu** [comment]
Hidden fields are ignored.

**Comment by phpsystems** [comment]
By hidden view, I mean more hidden from view, rather than the hidden tag.

**Comment by phpsystems** [comment]
And if the CSS has placed an object over it?

**Comment by varjolintu** [comment]
Not sure about that. I'm currently making a test case for these kind of situations. If that has been possible before, not in the future.

**Comment by toryth** [comment]
This also happens with https://id.atlassian.com.

I'm using Firefox.

Selecting the fields was difficult (or impossible), I ended up manually updating the storage.js file in the mozilla extension settings folder.

I am able to use the "fill username + password" function for the username, press enter, then separately use the password only after I get to the second view that contains the password. 

When pressing enter on the username it complains about not being able to find fields but does enter the username. Presumably it is looking for the password field.

Right clicking the password field is very difficult, I have to use the keyboard shortcut.

**Comment by AdamPS** [comment]
[Google](https://accounts.google.com) is a good example of a site that prompts first for a username then you have to submit before getting a new page that prompts for the password.

It doesn't work at first, but it works fine after I do "Choose custom login fields for this page".

So I wonder if this issue can be closed?

**Comment by varjolintu** [comment]
Proper way to do that is to add `https://accounts.google.com/*` to Site Preferences in the extension's settings and enable _Username-only detection_. After that the filling should work like a charm.

**Comment by droidmonkey** [comment]
We should really work on adding the "common sites with multi-page login" feature.

**Comment by AdamPS** [comment]
I confirm that "Username-only detection" also works, so I think this issue can be closed.

As a side note, can anyone explain why it is necessary to have a list for "Username-only detection"?  It would be much easier if it just worked automatically.  I was using Roboform before and it worked fine like that.

**Comment by varjolintu** [comment]
@AdamPS That list is needed because there's no standard way to define a single username field. It's quite hard to separate it from a search field or another single input field that exists on the page. While it would be easy to ignore any inputs fields that has `search` in the class list or id, everyone doesn't use it that way. I have seen pages with a search field and the only thing that gives a clue about it being a search field (input type was `text` as normally) that the id was "s".

Having these single input fields working "automatically" would trigger constant requests for giving permissions to the entries. That would happen on each tab change, page load etc..

**Comment by AdamPS** [comment]
@varjolintu Thanks for explaining.  I agree that the add-on cannot just guess something might be a username field and attempt to fill it.

However what about when the user navigates to https://accounts.google.com/ and presses AS+U?

**Expected behaviour**: fill the username only (safe assumption that the user wants this because they explicitly asked for the form to be filled)
**Current behaviour**: nothing happens

**Comment by varjolintu** [comment]
@AdamPS That's one thing we shoud improve: if the user wants to fill a single field with username or password, it should do so without any extra settings. Username and password field combinations are a different thing.

**Comment by AdamPS** [comment]
Great thanks I raised #513

**Comment by yichangshengwu** [comment]
another example : https://accounts.firefox.com/

**Comment by varjolintu** [comment]
I think this is not a problem anymore. Username should be always correctly filled with the "Fill Username and Password" if it's the only field visible.
