### ISSUE TITLE
Autofill extremely inconsistent

### ISSUE THREAD

**Issue by jwerrell** [keepassxreboot/keepassxc-browser#1678]
## Expected Behavior
 Keepassxc should autofill username and password into the appropriate fields on a website.

## Current Behavior
Very rarely will this work as intended. Usually the key icon will show up but it will be greyed out and nothing will happen when I click, double click, hold down, or do anything to it. Sometimes, not always, I will get the Browser Access Request for a site and if I check remember it usually won't work again if I logout and try to log back in. If I do not check remember it will sometimes, not always, let me login and logout multiple times. One time a site was working properly but then was being incorrectly auto-filled to a completely different domain. When I delete the database from the extension setting and reconnect it resets everything but the behavior is different pretty much every time. 

## Possible Solution
 I believe the database is having some issue syncing. In the Connected Databases tab of the extension's setting it says "No connected databases found," yet when I click on the extension it says it is connected. I'm not good with this stuff but I know it can't be connected and not connected at the same time but it seems to not know which it is.

## Steps to Reproduce (for bugs)
 I am using firefox on macOS. Everything else is pretty normal.

1. Install keypassxc and firefox on mac
2. Create passwords and sync database with extension
3. Try to use extension to autofill

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 2.7.1?
Operating system: MacOS 12.3.1
Browser: Firefox 102.0.1

Side note, if this is a lost cause does anyone recommend any other password managers whose autofill works with firefox?

**Comment by droidmonkey** [comment]
Probably fixed with #1676. Wait for extension version 1.8.1 to be released and test again.

**Comment by varjolintu** [comment]
It seems there are multiple issues here:
1. If you get the gray icon it usually means your entry URL is wrong.
2. Syncinc issues with the database and Connected Databases tab indicates that you are possibly using two databases with the same Root UUID? You can generate a new UUID in the Database Settings. Give it a try.
3. Not able to fill after Access Confirmation dialog is a known issue where messages between browser and KeePassXC gets out-of-sync because the Access Confirmation dialog blocks other messages. This happens especially if you forgot the dialog, or for some reason it's not brought to the front and you continue doing something else. The solution is already under implementation, but yes, it's an annoying issue. Using "Remember" setting is one workaround for it until the issue is solved.

**Comment by jwerrell** [comment]
Messed around with the URLs and changed the UUID and that seemed to fix things mostly. There are a few random website that don't autofill (the main one I can think of is gog.com) but otherwise it seems to be working, thank you!

**Comment by varjolintu** [comment]
I'll check the gog.com. Glad it's working otherwise.
