### ISSUE TITLE
Form fill fails with error: "credential list is empty"

### ISSUE THREAD

**Issue by PhoenixClank** [keepassxreboot/keepassxc-browser#1744]
## Expected Behavior
My saved credentials are filled into the login form when I click the icon in the username field.

## Current Behavior
Nothing happens.

## Steps to Reproduce (for bugs)
1. navigate to a site I have saved credentials for
2. click the icon in the username field
3. (unlock the database)

## Debug info
```
[Debug keepassxc-browser.js:203] KeePassXC-Browser - Input fields found: global.js:170:13
Array [ input#XMKIHtwlSiDOFJKw.nbf-text-input, input#JzKrrynqmrbSNMEX.has-inline-icon.nbf-text-input.format-password-show ]
global.js:173:17
[Debug keepassxc-browser.js:209] KeePassXC-Browser - Login field combinations identified: global.js:170:13
Array [ {…} ]
global.js:173:17
[Debug fields.js:169] KeePassXC-Browser - Input fields found: global.js:170:13
Array [ input#XMKIHtwlSiDOFJKw.nbf-text-input, input#JzKrrynqmrbSNMEX.has-inline-icon.nbf-text-input.format-password-show ]
global.js:173:17
[Debug fields.js:193] KeePassXC-Browser - Login field combinations identified: global.js:170:13
Array [ {…} ]
global.js:173:17
[Debug username-field.js:175] KeePassXC-Browser - Error: Credential list is empty. global.js:170:13
```

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.2.2
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Give an example of a site that does not work, including your entry URL? Maybe it's not correct and the matching does not work.

**Comment by PhoenixClank** [comment]
Site I'm trying to login on: https://www.ksklb.de/de/home/login-online-banking.html?stref=login&n=true
URL in the entry: https://www.ksklb.de

**Comment by varjolintu** [comment]
I had absolutelu no problem with the site. Does restarting KeePassXC help?

**Comment by Dboy-Even** [comment]
Hi,

I had a similar behavior
- Browser : `Vivaldi 6.0.2979.22 (Stable channel) stable (64-bit)`
- OS: `archlinux 6.1.30-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 24 May 2023 17:18:57 +0000 x86_64 GNU/Linux`
- keepassxc :
```
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.1.30-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0
```
- keepassxc-browser (vivaldi is based out of chromium):
```
KeePassXC - 2.7.5
KeePassXC-Browser - 1.8.6.1
Operating system: Linux x86_64
Browser: Chrome/Chromium 112.0.0.0
```

The websites on which it occurs is varying:
- proxmox 7 management interface
- pfsense management interface
- ovh website
- github website


This problem seems to occur when the synchronization between the `keepassxc-browser` and `keepassxc desktop` does not work like this:

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/9354740/04b3ee7f-9379-42fd-b5d2-e94cc0f27df4)

This started after an update of both the desktop and browser-extension (at a boot apart).

The screenshot appeared after completely resetting the browser extension and the connection to the browser and then, reinitialize everything.

Usually, even in this situation, I manage to get it working by : 
- re-connecting the extension (hitting `reload`), 
- trying to get web entry filled (usually nothing happens)
- finally, restarting the browser extension (disable-enable)

Hope this helps,
If you need any more information, ask away ;)

**Comment by varjolintu** [comment]
Let's reopen this if some response is received.
