### ISSUE TITLE
Delete master branch?

### ISSUE THREAD

**Issue by stefansundin** [keepassxreboot/keepassxc-browser#1757]
Anytime I want to contribute to this repository I am confused about the branches. Just now I accidentally tried to rebase my branch against `master` (because of muscle memory). If the branch hadn't existed then at least the command would have failed but since the branch exists it gave me a very long rebase list that I had to abort.

So I think the fact that the master branch exists but is not the main branch is a bit confusing. It seems like it was used previously and can probably be deleted now?

Ideally it would be nice if `main` was used instead of `develop`, but since the main KeePassXC repository also uses `develop` it would be a much bigger discussion. In my opinion `main` is more convenient than `develop` since it is what most projects use these days. Using a more common branch name will just make the git workflows more familiar to more people. Has this already been discussed somewhere?

**Comment by varjolintu** [comment]
This haven't been discussed before, so thanks for bringing it up. The whole mess is because `master` branch is protected, which means updates cannot be pushed to it directly. Updating the `master` branch would mean a separate PR for `develop` -> `master`.

So currently the workflow is:
- `develop` branch is for the new fixes and features. It's always up-to-date.
- `release/1.8.x` (for now) is updated after a new release

**Comment by stefansundin** [comment]
I think branch protection can be disabled. I don't even think it is the default so it was probably set up at some point.

**Comment by varjolintu** [comment]
> I think branch protection can be disabled. I don't even think it is the default so it was probably set up at some point.

Could be. I don't have any permissions to do that though. Any help here @droidmonkey?

**Comment by phoerious** [comment]
I deleted the master branch.
