### ISSUE TITLE
Password and TOTP in one field

### ISSUE THREAD

**Issue by hofq** [keepassxreboot/keepassxc-browser#1838]
## Expected Behavior

If i login in Services Protected by FreeIPA LDAP, i want to autofill `Password + TOTP` like i can copy it from the KeePassXC-App with this Button:
![image](https://user-images.githubusercontent.com/54744977/214523828-5447ce5a-d639-4196-8ab4-3b690329370c.png)

I would like to be able to select a field in which Password + TOTP will be inserted, or configure to be every password field with this credentials be filled with the Password and TOTP

## Current Behavior

I just cant figure out how to set TOTP and Password to be on the same field, so i have to copy it from the Desktop App every time.

## Possible Solution

Maybe add an Option to the Entry itself via the extra wars that allows me to change if only the password or the password and totp gets inserted

## Steps to Reproduce (for bugs)

1. Have an Entry that has configured TOTP in KeePassXC
1. Go to a Website covered by LDAP and TOTP (ideally covered by FreeIPA over LDAP)
2. click on the entry and only the password gets filled
3. switch to custom fields and only be able to select password or TOTP

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Use this method:
- Add a new attribute to your entry named `KPH: Password and TOTP`
- Set the value of the attribute to e.g. `{Password}-{TOTP}` (or whatever is the form this needs to be)
- Go to the login page and right-click the password field with mouse. Choose `Fill Attribute` and you should see the previously added  `Password and TOTP` in the list.
- The field should be filled with the correct value

You can also automate this by selecting Custom Login Fields for the site and select Username field normally, but no password field, but a String Field instead of it. The String Field should fill that new `KPH: ` field automatically.

**Comment by hofq** [comment]
Okay, Thanks! Its not that perfect but does what i want.

Thanks for your Quick Help!

**Comment by lw-davida** [comment]
Is it outside of the scope of this plugin to change this issue to a feature request?  

> Use this method:
> ...
> You can also automate this by ...

Since KeepassXC has a keyboard shortcut to auto copy **{Password}{TOTP}**, I feel like there could be something similar in this extension to simplify this?

> Maybe add an Option to the Entry itself via the [additional attributes] that allows me to change if only the password or the password and totp gets inserted

When I ran into this issue recently, this too seemed like an ideal solution (if it was possible).  
To this idea, if there's the hypothetical attribute was not present under an entry, then the default behavior can be to just fill the password.

> Set the value of the attribute to e.g. `{Password}-{TOTP}` (or whatever is the form this needs to be)

KeepassXC's shortcut just appends the TOTP, which is how FreeIPA etc expects it.
https://github.com/keepassxreboot/keepassxc/blob/a0874a0d6de732f75241ffe515623fd0d410c51b/src/gui/DatabaseWidget.cpp#L657

**Comment by varjolintu** [comment]
@tweetle-beetle This was not automated enough? https://github.com/keepassxreboot/keepassxc-browser/issues/1838#issuecomment-1403318703

**Comment by tweetle-beetle** [comment]
The solution worked adequately. I just wanted to share my feedback since it was difficult to find this solution. Thanks again.
