### ISSUE TITLE
Reload button barely visible in the "More tools..." popup menu on Firefox

### ISSUE THREAD

**Issue by DarkReaper231** [keepassxreboot/keepassxc-browser#1844]
![image](https://user-images.githubusercontent.com/38611351/215929649-c30bc256-9b88-4f0f-85d4-37b2f054cbdf.png)

## Expected Behavior
The button should stay within the regions of the popup

## Current Behavior
It doesn't

## Possible Solution
Make the width dynamic, a lot of addons have it that way so they can fit this popup menu nicely. I am not sure what are the exact dimensions of the popup tho. Otherwise moving the button a bit would also fix it.

## Steps to Reproduce (for bugs)
Move KeePassXC addon to this overflow menu in the "Customize Toolbar"

## Debug info
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Arch Linux
Browser: Firefox 109.0

**Comment by varjolintu** [comment]
This should've been already fixed in https://github.com/keepassxreboot/keepassxc-browser/pull/1571. A related issue: https://github.com/keepassxreboot/keepassxc-browser/pull/1771

Gotta check if something has changed. In my Firefox there's no longer the overflow menu available. Should `extensions.unifiedExtensions.enabled` to be disabled?

**Comment by DarkReaper231** [comment]
> This should've been already fixed in #1571. A related issue: #1771
> 
> Gotta check if something has changed. In my Firefox there's no longer the overflow menu available. Should `extensions.unifiedExtensions.enabled` to be disabled?

That's weird, I have old version of the addon. But I swear to got I had 1.8.4

**Comment by DarkReaper231** [comment]
Well it works now after I reinstalled the addon
