### ISSUE TITLE
What goal does the protocol encryption serve?

### ISSUE THREAD

**Issue by palant** [keepassxreboot/keepassxc-browser#1884]
I am reimplementing the KeePassXC protocol in order to use it in my own browser extension. I have no trouble understanding the protocol, but I have issues understanding the design goals behind it. In particular, what’s the goal of encrypting communication that never leaves the computer? I’ll outline my understanding of the possible attack scenarios here, maybe I’m missing something.

Typically, the goal of encryption is addressing MITM attacks. For example, some malware might have replaced the KeePassXC proxy by a malicious one. The protocol does *not* address this scenario however because both host and client keys are temporary. So a malicious proxy could communicate its own host key towards the extension and its own client key towards the real proxy. This would allow it to decrypt and arbitrarily modify the messages as they pass through it.

Ok, maybe this is only about addressing passive eavesdropping. Still: what kind of privileges are required in order to eavesdrop on a native messaging connection? The malware must be running either as the current user or the administrator. Both should be sufficient to compromise the KeePassXC database by simpler means, e.g. by recording the database password as it is being entered.

Public key cryptography also allows identifying endpoints. KeePassXC doesn’t actually do that. The “identification key” is merely an identification token – it is never used to encrypt/sign anything, the secret key is being dropped. So the identification here relies on the browser keeping the extension’s identification token safe. Which is fair enough – if a malware can extract a token from the extension storage, it will also be able to get whatever keys are stored there.

So, what is the attack scenario that all this public key cryptography is mitigating?

**Comment by varjolintu** [comment]
Basically in the early days I wanted to encrypt the communication for a couple of reasons:
- The original KeePassHTTP was lacking that (a safe one), plus the communication went through a simple TCP socket. This extension also did that before moving to Unix sockets and pipes.
- I wanted to keep the option open that you could potentially communicate safely outside your local computer. For example I've been tempted to test a `keepassxc-server` or something similar that could work as a read-only database accessed remotely (for groups that need no write permissions etc.). In short, the encryption is there just-in-case for future scenarios.

The reason for temporary keys for the connection and permanent keys for the identification also comes from the design faults in KeePassHTTP. In that protocol every connection was stored to the browser using the actual communication keys, and those were always reused, which is of course shouldn't be done. Instead the identification keys are now permanent but connection keys are always temporary. And those are not mixed up. At least this should make passive eavesdropping a bit more difficult with the encryption in communication level.

Concerning possible malware, the following problems should be somehow resolved:
- [Protecting](https://github.com/keepassxreboot/keepassxc-browser/issues/678) the localStorage. Currently no browser does this. The only option would be encrypt the localStorage from the extension. And of course that would need another password or non-safe verification for decryption. Which is related to the next problem.
- Connection keys should be stored to the computer's keychain etc. instead of localStorage. This would hopefully prevent any fraudulent software to get any connection keys from the browser, or at least it could make it slightly more difficult.
- Native Messaging does not (and cannot) identify the child process it launches. If the Native Messaging JSON script has been changed manually or by some other application, the API provides no way to ensure the proxy (in this case) is a valid application that hasn't been modified in any way. Is there a reliable way to somehow verify a binary is not altered?

> Which is fair enough – if a malware can extract a token from the extension storage, it will also be able to get whatever keys are stored there.

This is the reason KeePassXC enables a separate Access Confirm dialog when credentials are accessed via the extension API by default. Even if there would be a fraudulent application receiving your credentials when your database is open, at least it gives the user an indication that something is trying to access your connected database. This of course doesn't prevent a scenario where the whole proxy has been replaced. Unless the proxy is in a location that cannot be replaced by the user without admin permissions.

**Comment by palant** [comment]
> I wanted to keep the option open that you could potentially communicate safely outside your local computer.

Quite frankly, this scenario sounds like something better solved by routing the usual protocol through TLS rather than some custom encryption scheme. Even with a self-signed server certificate, TLS will provide stronger security guarantees. And it wouldn’t complicate the protocol unnecessarily.

> Protecting the localStorage.

The question here is also: what issue does that solve? Do the browser and KeePassXC application ever run under different user accounts? If not, there are simpler way to get the passwords out. The typical one is extracting the encryption credentials via a keylogger. Or, if the database is unlocked (which it has to be for the extension to work), encryption key should be possible to extract from the process memory.

> Even if there would be a fraudulent application receiving your credentials when your database is open, at least it gives the user an indication that something is trying to access your connected database.

Which is why this fraudulent application is more likely go for the KeePassXC application directly as I said above.

Generally, protecting against malware involves not getting malware onto a computer in the first place. Once it’s there, it’s usually a lost cause.

> Unless the proxy is in a location that cannot be replaced by the user without admin permissions

There is a per-user native manifest file for the proxy. Even if the proxy itself cannot be modified, it’s always possible to modify the native manifest in order to point it to a different executable.

> I'd be happy to provide a V2 of it some day that could potentially make it safer and simpler.

A version without encryption, merely with a client identifier, and proper matching of requests to responses would make me happy.

**Comment by droidmonkey** [comment]
This isn't "custom encryption", it is libsodium's crypto box, which is a simplified way to transmit encrypted data using public key cryptography. Your argument to have no encryption at all is rather silly.  If you have a chance to at least protect data you should take that chance. It is rather easy to eavesdrop on IPC communications using local sockets (which is how the proxy communicates with keepassxc).

**Comment by varjolintu** [comment]
> Generally, protecting against malware involves not getting malware onto a computer in the first place. Once it’s there, it’s usually a lost cause.

Which is why it's quite hard to protect against memory extracting etc. especially when considering browsers. In KeePassXC there's some [protection](https://keepassxc.org/blog/2019-02-21-memory-security/) though. With cloud-based password managers there are still open issues about master password having found inside the browser instance. Which is why we don't encourage entering your master password anywhere outside KeePassXC. Even if someone could get a indentification key of your KeePass database, the Access Confirm dialog should warn you, also in cases where the fraudulent application targets KeePassXC directly.

> There is a per-user native manifest file for the proxy. Even if the proxy itself cannot be modified, it’s always possible to modify the native manifest in order to point it to a different executable.

Sure. AFAIK there's no protection against this.

> A version without encryption, merely with a client identifier, and proper matching of requests to responses would make me happy.

That's probably not going to happen, but I have already some plans for V2, and I've already made some progress to decrease the amount of messages needed for some simple tasks. Where V1 is mostly just an improved version of KeePassHTTP's protocol, the new implementation will divert from it.

**Comment by palant** [comment]
> This isn't "custom encryption", it is libsodium's crypto box

I said “custom encryption scheme.” It’s not merely about the choice of algorithms, the tough part in public key cryptography is making sure the other side’s key can be trusted.

>  If you have a chance to at least protect data in motion, you should take that chance.

I’m told that security by obscurity has its place in some cases. I’m just not sure whether an open source application can ever count on it however. And if we are talking about something targeting KeePassXC proxy specifically, then it’s not a generic attack that might miss attack surface.

This encryption scheme comes at a high cost. There is considerable effort sunk into developing and maintaining it. It needs to be documented. It turns off potential contributors, even people who merely want to figure out an issue they are experiencing. So it better be worth it.

**Comment by droidmonkey** [comment]
> the other side’s key can be trusted.
That is false. This only matters for authentication, not for encryption. We handle authentication through the pre-shared secret, which happens when you connect the extension to a database.

**Comment by palant** [comment]
> This only matters for authentication, not for encryption.

It matters whether Alice encrypts the message with Bob’s public key or with Mallory’s. As things stand right now, KeyPassXC’s protocol doesn’t allow telling which one is which.

**Comment by palant** [comment]
I think that I got my answer, closing the issue.

**Comment by droidmonkey** [comment]
Good discussion though, made me think

**Comment by varjolintu** [comment]
Same here. Thanks for the input.
