### ISSUE TITLE
HERE Maps login not working

### ISSUE THREAD

**Issue by bceylon** [keepassxreboot/keepassxc-browser#1899]
Problems with HERE Maps login page: https://account.here.com/sign-in

With this page, there's no browser add-on icon visible, also selecting custom login fields does not color existing input fields. It's not possible to enable this site for browser integration.

## Debug info
JavaScript console: InstallTrigger is deprecated and will be removed in the future.
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.6.1
Operating system: Mac
Browser: Firefox 112.0

**Comment by varjolintu** [comment]
This happens because the form that includes the input field is defined with a height of zero. Extension thinks this form is possibly a fraudulent one, and it is ignored.

Those fields are inside a Shadow DOM and the extension supports them only partially so the Custom Login Fields will not work here either.

Auto-Type is your only solution here.
