### ISSUE TITLE
Keepassxc and Chatgtp/openai access

### ISSUE THREAD

**Issue by jnilo1** [keepassxreboot/keepassxc-browser#1900]
Hello. I am new to keepassxc and find it a great app ! But I am still having difficulties to record login credentials in certain type of situation. For example when I want to get connected to https://chat.openai.com/ I am unable to get access to my email address from keepassxc (I have to retype it each type and I do not see the keepass logo) whereas the password is found without any problem from keepass. Am I missing something or is there an way to resolve that issue ? many thanks !

**Comment by droidmonkey** [comment]
@varjolintu we are going to have to add an exception for this site. I couldn't get anything to work properly.

**Comment by varjolintu** [comment]
I could get the credentials work normally by:
- Enable Username-only Detection for the site
- Entry with `https://openai.com` as URL
- Use the Autocomplete Menu or toolbar icon to fill credentials

The only thing that is not working is the Username Icon. This happens because the page does not respect the standards. They are setting a HTML button element as `form.action` which should not be accepted. The extension ignores the form because `form.action` is not a string. Ignoring the form here means we are not listening for any possible submits. 

However, this should not affect setting the icon. The bug happens when there are no forms identified in the internal list, but the code still ignores any inputs inside forms later. Need to add an extra check that if there are no identified forms, it allows the icon to be set.

**Comment by jnilo1** [comment]
Thank you for this explanation. As mentionned in my initial post the password entry works just fine but the issue is indeed the username input. Enven when you choose to enter the username through keepassXC-Browser the field 'username' appear in the login field but its content is not there.
BTW I get the impression that this situation is not uncommon. For example when I try to connect to my bitdefender account through https://login.bitdefender.com/ I have the same problem. Perhaps because they want to discourage users moving away from their own password manager solution... which is precisely what I want to do :-)

**Comment by varjolintu** [comment]
Username-only Detection needs to be enabled manually for some sites. We don't do this automatically because of a lot of false positives.

**Comment by f-hollow** [comment]
Took me a while to figure out where to enable Username-only Detection. Finally, found the answer [here](https://github.com/keepassxreboot/keepassxc-browser/issues/159#issuecomment-487279810):

Go to the KeePassXC browser extension's settings > Site Preferences > add URL `https://openai.com` manually and select the option `Username-only Detection`.

**Comment by Cyber-Syntax** [comment]
After the changes from chatgpt, it's now using 2 URLs to login: 
1. For username-only authentication, it uses `https://auth.openai.com/`.
It detects this URL in the entry field and proceeds.
However, after proceeding further, it sends a second URL:
2. `https://auth0.openai.com/` which shows password-only authentication but KeepassXC can't see because we can only use one URL on the entry?
Please reopen the issue @varjolintu.

**Comment by varjolintu** [comment]
@Cyber-Syntax Use `https://openai.com` as your entry URL. Multiple URLs are also possible if you edit the entry (in Browser Integration page), but that is not necessary. Just using the plain domain name accepts all subdomains.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_usage
