### ISSUE TITLE
KeyPassXC cannot connect to KeyPass browser

### ISSUE THREAD

**Issue by TheInterplexium** [keepassxreboot/keepassxc-browser#1906]
I cannot connect KeyPassXC to KeyPassXC browser 

## Expected Behavior
I am using FireFox Nightly Version 114.oa1 (23-4-28) (64-bit). KeyPassXC has support for FireFox browsers but what about other versions of FireFox

**##Current Behavior**
Id suggest adding support for other versions of other browsers like FireFox

KeePassXC - 2.7.4
KeePassXC-Browser - 2.7.4
Operating system: Win
Browser: Firefox Nightly Version 114.oa1

**Comment by TheInterplexium** [comment]
This is my first time opening a Issue so please don't criticize me :(

**Comment by droidmonkey** [comment]
We don't support nightly or beta builds of browsers.

**Comment by pallaswept** [comment]
I have filed a bug with mozilla, adding your voice there may help this to get attention from them: https://bugzilla.mozilla.org/show_bug.cgi?id=1830605

**Comment by varjolintu** [comment]
@pallaswept Beta and Nightly builds have constantly something broken, and it's pretty usually something related to Native Messaging. I'm not expecting that even Mozilla does anything about it. If the Native Messaging itself is not broken, some browser API's can be broken. Which is the reason we cannot support Beta/Nightly.

**Comment by pallaswept** [comment]
> the reason we cannot support Beta/Nightly.

I understand, and I agree; for you to support nightly/beta builds would be totally impractical. 

But it does make sense to send bug reports upstream. They won't get fixed by magic, and it will be easier to squash them sooner than later, because whoever broke it is still working on it right now, but later on when it's in the release build and you will be asked to support it, that developer will be busy elsewhere, and it'll take a lot more time and effort to get them back to look at it again. They also will pay more attention to the actual developer of an addon, feeding them a report of a widespread issue, than to a random nobody user like me with a one-off report.

As it happens, #1905 found the root cause and it is the treatment of unix-style slashes in file paths, as detailed [here](https://github.com/keepassxreboot/keepassxc-browser/issues/1905#issuecomment-1528753623). I've forwarded this on to the bugzilla report, so hopefully it'll all get fixed without any further effort from your team.

**Comment by droidmonkey** [comment]
You, as the user of the nightly build, should send the bug report to Mozilla first. We will not file bug reports on your behalf.

**Comment by pallaswept** [comment]
> > But it does make sense to send bug reports upstream
> 
> You, as the user of the nightly build, should send the bug report to Mozilla first. We will not file bug reports on your behalf.

I have done so, but as I said, they'll naturally pay more attention to someone like you - an active developer of a popular and important addon, reporting a widespread issue; than someone like me - a random end-user reporting a one-off problem.... so your voice carries weight here, which can eventually reduce workload on your team through expediating resolution of the bug before it becomes embedded, so it would be unfortunate to simply refuse to be involved.

I'm just following ITIL standard process and common sense here, but nobody is forcing you to take action, so don't worry about it :)

**Comment by droidmonkey** [comment]
Thanks for reporting but we are random users just as much as you are to Mozilla. We don't use nightly browser builds and for us to submit a ticket then obligates us to respond and test a fix. That doesn't follow ITIL. Plus we aren't a support desk either.

**Comment by varjolintu** [comment]
@pallaswept The time I have for development, I'll use it for the extension and KeePassXC. Testing Beta/Nightly browsers doesn't improve the quality of the extension. The scope is totally different. For me, it would be just a waste of time.

**Comment by pallaswept** [comment]
Well that's a shame to hear, one would like to think they'd treat a dev, especially one from an important and very popular addon, with a bit more respect than some random user. Sorry to hear it.

If you do file the bugzilla bug on behalf of the users who report issues here, you can delegate any further interaction like testing to the original bug reporters (us here in these issue reports) but regardless.... for future reference, if you ever need a nightly user to test stuff for you, you are very welcome to ping me, I'd like to help out your project in any way I can, and I need to use nightly, so please feel free put me to work if you ever need it.

**Comment by droidmonkey** [comment]
We have found that nightlies end up making you chase your tail, and the devs often know something is broken and fix it without a report. I am surprised they don't have automated testing around native messaging, which is a thing they often break in nightlies. Anyway, thank you for the support.

**Comment by pallaswept** [comment]
> We have found that nightlies end up making you chase your tail

Ain't that the truth. Funnily enough the reason I need to use it is because I have a bunch of userchrome mods I need to help with accessibility, and if I'm on nightly then I get to fix them one-by-one (chase my tail) rather than getting a giant stack of breakage that's unmanageable.



> the devs often know something is broken and fix it without a report

I've noticed this too. Well this time, they know about it for sure, so hopefully all this won't take any more of your valuable time. Thanks so much for the addon.

**Comment by pallaswept** [comment]
> I am surprised they don't have automated testing around native messaging

You may be pleased to hear that there is now a patch submitted to the bugzilla report which has two parts - firstly it replaces unix-style / slashes with double-backslashes \\ (fixes unix paths on windows) and secondly, adds a test for this part of native messaging. 3 lines of code for the fix and 29 for the test. So, they;re on your wavelength :)
