### ISSUE TITLE
Start+Login to keepassxc first before starting Edge to be able to connect

### ISSUE THREAD

**Issue by tuxedo0801** [keepassxreboot/keepassxc-browser#1926]
Using Keepassxc on Win10 with Edge browser. Works in principle. BUT: I always need to start Keepassxc and do login to DB first, before starting any Edge instance. Otherwise, connection is not possible. Means:
If I start Edge 1st and Keepass 2nd, I never get a connection.

Why is this? How can I overcome this? Any ideas? Troubleshooting guide did not help so far.

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.6.1
Operating system: Win64
Browser: Microsoft Edge 114.0.1823.43

**Comment by droidmonkey** [comment]
There really is no reason why you would need to sequence of edge vs keepassxc. That is definitely not the normal behavior of our program. This makes it nearly impossible to debug your situation since it is likely something unique to your deployment. 

Please detail exactly what steps you have tried in troubleshooting and what error messages you see.

**Comment by varjolintu** [comment]
You can connect to KeePassXC for example just clicking the Username Icon on a page. Another way is to open the extension popup from the toolbar icon and reload the connection from there.
