### ISSUE TITLE
Unable to reach in-page dialog buttons using keyboard

### ISSUE THREAD

**Issue by DavidPesticcio** [keepassxreboot/keepassxc-browser#2031]
## Expected Behavior
When prompted to save or update credentials, or dismiss dialog, should the user be unable to access the in-page dialog buttons?

## Current Behavior
Unable to use the keyboard to access in-page dialog buttons.

## Steps to Reproduce (for bugs)
1. Visit website and enter details not known to KeePassXC
2. Enter credentials
3. Wait for in-page KeePassXC dialog to appear
4. Use keyboard to reach dialog button - not possible, is this expected?

## Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.9
Operating system: Linux x86_64
Browser: Chrome/Chromium 119.0.0.0

**Comment by varjolintu** [comment]
I'm pretty sure this has been requested earlier that the buttons should be accessible. Let's keep this open anyway.

**Comment by varjolintu** [comment]
Just tested this and you can reach the buttons using <kbd>Tab</kbd> or <kbd>Shift</kbd>+<kbd>Tab</kdb> normally. Did you possibly mean that you wanted to access the buttons using some keyboard shortcuts? That would be a difficult one because we want to keep the page usable at the same time.

**Comment by DavidPesticcio** [comment]
Ah, so you can... :facepalm: :+1: 

The website I was on when I tried <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> jumped over the in-page dialog when using <kbd>Shift</kbd>+<kbd>Tab</kbd> several times from the login box and it jumped into the browser buttons, and it was miles away when using <kbd>Tab</kbd> - it appears that the in-page dialog is actually last in the page. I obviously didn't go back enough times to skip over the browser buttons to reappear at the bottom of the page, which then takes me to the in-page dialog at the top.

I presume there's no way to make the in-page dialog appear earlier in the ordering? Although I guess that will also be a case of six of one and half a dozen of the other as there could be many things to <kbd>Tab</kbd> over anyway, what with all the links some pages have on them. As you say though, a shortcut could cause other problems...

Just a thought, but would it be possible to add a button to the extension, for keyboard users, that allows the user to jump to the first button of the in-page dialog? :thinking:

i.e. Activate the extension, then a button to jump to:
```
<button class="kpxc-button kpxc-green-button" id="kpxc-banner-btn-new">New</button>
```

If not, no worries, at least I know it can be reached now! :rofl:  

Thanks.

PS. Feel free to close this issue. :+1:

**Comment by varjolintu** [comment]
> I presume there's no way to make the in-page dialog appear earlier in the ordering? Although I guess that will also be a case of six of one and half a dozen of the other as there could be many things to Tab over anyway, what with all the links some pages have on them. As you say though, a shortcut could cause other problems...

Thanks the thing: we append all items to DOM to the Shadow DOM, and it's always to the end of the page. So normally the page content doesn't even have an access to it. And defining a `tabIndex` to elements inside the Shadow DOM seems to have no effect.

In the old implementation we had keyboard shortcuts for each selection and operation, but in that case we put an overlay to the web page and you couldn't use it at all. The reason that changed was because users wanted to have the possibility to operate the page, switch page, wait for password field to appear etc.. So it was decided that this is more important than keep the static overlay on the page.

Maybe we could add some keyboard shortcuts for the main buttons in the Credential Banner but it could interfere with the normal keyboard input, for example when entering credentials. I hope this clears the issue a little bit.
