### ISSUE TITLE
Browser plugin should poll for running instance of KeepassXC

### ISSUE THREAD

**Issue by gareththered** [keepassxreboot/keepassxc-browser#2261]
If I start a browser (Edge, Chrome, Firefox on Windows; Chrome, Chromium, Firefox on Debian) and later open KeepassXC then the browser plugin doesn't automatically connect. 

## Expected Behavior

The browser automatically connects to KeepassXC when it starts.

## Current Behavior

I have to manually click on the Reload button on the plugin on each browser for them to connect.

## Possible Solution
 The browser plugin periodically polls for KeepassXC and automatically connects.

## Steps to Reproduce (for bugs)

1. Start browser(s).
2. Start KeepassXC
3. Check plugin status or attempt to login.

## Debug info

KeePassXC - 2.7.9 (Installed on Windows, AppImage on Debian)
KeePassXC-Browser - 1.9.0.5
Operating system: Win 11 & Linux (Debian)
Browser: Chrome/Firefox/Edge/Chromium

**Comment by varjolintu** [comment]
We have disabled the automatic reconnect function because it has unsolved [memory leaks](https://github.com/keepassxreboot/keepassxc-browser/issues/1113). Pinging without the connection cannot be done. This feature should be done inside the proxy, but it has its own issues why this is not easy.

Anyway. This is a duplicate feature request. You can already reconnect the extension without the popup just by clicking the Username Icon at the side of the input field.
