### ISSUE TITLE
[Request] Connect KeePassXC-Browser to Docker Image

### ISSUE THREAD

**Issue by Querzion** [keepassxreboot/keepassxc-browser#2271]
I have just been using a local install for years, now but I tend to install and delete VM's very often, it's come to the point off irritation that I can't just connect directly to my unRaid docker image (that has the latest KeePassXC installed), that I started to look up how to install Brave & KeePassXC into the docker. I haven't found any guides, so I suppose it's not possible atm. (To connect the extension to a docker image. I think It has to be an official image though since it becomes isolated. "/ )

**Comment by varjolintu** [comment]
Related: #394.

**Comment by droidmonkey** [comment]
Running gui applications in docker containers really defeats the purpose of docker since you have to basically deisolate to make them work properly. You are much better off using a proper isolation technique like apparmor, snap, flatpak, etc. Docker is not a same-system isolation technique, it is meant for self contained services that expose a defined interface (ideally via tcp/ip). Wayland might be a controlled way to expose gui in docker, but certainly not X11.
