### ISSUE TITLE
Issue connecting more then 4 DBs with Browser Plugin

### ISSUE THREAD

**Issue by Seulasslintan** [keepassxreboot/keepassxc-browser#2368]
## Expected Behavior
After connecting more than 4 KeePass databases using the plugin on Mac with Firefox or Chromium, all connections should be listed in the plugin and should function as expected.

## Current Behavior
It is possible to connect more than 4 databases without any issues. However, only 4 connections are displayed in the plugin settings. The displayed databases do not always reflect the currently connected databases. When reconnecting a database, the list of databases is not updated, although access to the "new" connected database is still available. At the same time, one random connection is removed from the list. Reconnecting a database with the same name causes KeePassXC to display a message indicating that the connection already exists.

## Possible Solution
Allow more than 4 databases to be connected and displayed correctly in the plugin.

## Steps to Reproduce (for bugs)
1. Connect the first database
2. Connect the second database
3. Connect the third database
4. Connect the fourth database
5. Connect the fifth database
6. Check the list of connected databases in the plugin settings.

## Debug info
KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.3
Operating system: Mac 15.0.1
Browser: Chrome and Firefox

**Comment by varjolintu** [comment]
Verified this and I cannot reproduce the bug. I'm pretty sure this is caused by your database where one of them is a clone from another. This means the root group UUID used to identify the database is identical with another database you are using simultanously. 

Do the following:
- Disconnect every database from the extension, from both extension side and KeePassXC (from Database Settings -> Browser Integration)
- Generate a new root grouo UUID for every database you use (this is also in Database Settings -> Browser Integration)
- Reconnect all database back to the extension

**Comment by Seulasslintan** [comment]
Hey varjolintu, that was exactly the issue! Thanks so much for your help!
