### ISSUE TITLE
Breaks fonts on most sites

### ISSUE THREAD

**Issue by Diadlo** [keepassxreboot/keepassxc-browser#244]
## Expected Behavior
Normal font on all sites

## Current Behavior
Font on page are large

## Steps to Reproduce (for bugs)
1. Go on https://duckduckgo.com
2. Search "Test search" (remember page render result)
3. Install plugin
4. Go on https://duckduckgo.com
5. Search "Test search"

## Debug info
No specific messages

KeePassXC 2.3.3
keepassxc-browser - 1.1.8
Operating system: Linux
Browser: Firefox
Proxy used: NO

Good:
![image](https://user-images.githubusercontent.com/6306608/43442268-2651a75c-94a6-11e8-8585-ff5c1ef590ec.png)

Bad:
![image](https://user-images.githubusercontent.com/6306608/43442274-2a658868-94a6-11e8-8e6e-a9d02a92e02f.png)

**Comment by varjolintu** [comment]
This is probably because of some jQuery collision in the content script. Still, it shouldn't make any changes to the content because the jQuery version with the extension is scoped. Does the page console say anything?

Btw, you claim you are using KeePassXC-Browser 1.1.8 but there's no such version even released.

**Comment by Nothing4You** [comment]
@varjolintu it has indeed been released: https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/versions/
I'm not sure though why firefox prefers the version released today over Version 1.2.0 from 2 days ago.

**Comment by varjolintu** [comment]
This was my bad.

**Comment by Diadlo** [comment]
Yes. Seems fixed in 1.2.

Thank you for the fast answer :)
