### ISSUE TITLE
Document how to make browser work within Sandboxie

### ISSUE THREAD

**Issue by xarx00** [keepassxreboot/keepassxc-browser#267]
For several hours, I was trying to persuade KeyPassXC-Browser to work within the Sandboxie environment. At last, I've made it work! As I found no clues online, I'm writing here just to help others who have their browser sandboxed too.

In Sandboxie:

- In Settings > Restrictions > Start/RunAccess add `keypassxc-proxy.exe`
- In Settings > ResourceAccess > FileAccess > FullAccess add `\Device\NamedPipe\*\kpxc_server`; you can restrict usage of this pipe just to the `keypassxc-proxy.exe` application.

I have Windows 7 Pro x64, Sandboxie 5.26, KeePassXC 2.3.3, KeePassXC-Browser 1.2.0, Firefox 60.1.0esr x64.

**Comment by varjolintu** [comment]
Thank you for this! It will make a nice addition to the upcoming manual.

**Comment by RedTailBullet** [comment]
Possibly updated info.

KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Win10
Browser: Firefox

Sandbox setting -> Resource Access -> Add File/Folder -> Set the path to \Device\NamedPipe\org.keepassxc.KeePassXC.BrowserServer_*

Then your KeePass Browser extension should work as normal.

Hope this helps.

**Comment by masonh** [comment]
Similarly, on Linux, the socket is likely to be at ${XDG_RUNTIME_DIR}/org.keepassxc.KeePassXC.BrowserServer (e.g. /run/user/1000/org.keepassxc.KeePassXC.BrowserServer). Users of Firejail will need to add this to their browser profile's whitelist for proper functionality. Firejail uses $RUNUSER instead of $XDG_RUNTIME_DIR.

`whitelist ${RUNUSER}/org.keepassxc.KeePassXC.BrowserServer`

**Comment by omega3** [comment]
> `whitelist ${RUNUSER}/org.keepassxc.KeePassXC.BrowserServer`

@masonh masonh
Can you please tell me when am I suppose to paste it?

When I run firefox from terminal with simple command: `firefox`
KeepassXC connects to database = KeePassXC-Browser connects to KeePassXC

But I run firefox in firejail like this:
`firejail --private=/home/user/jail/  /usr/lib/firefox/firefox`

KeePassXC-Browser cannot connect to database. And I don't use any additional firejail configuration files.

I used to copy native-messaging-hosts folder from firefox running normally (without firejail) to Firefox running with firejail and it worked. But since KeepassXC 2.6.3 id doesn't work.
https://github.com/keepassxreboot/keepassxc-browser/issues/266

**Comment by masonh** [comment]
@omega3 
If you are using the default firefox firejail profile, you should be able to add the line to either a system-wide file at `/etc/firejail/firefox.local` or a user file at `$HOME/.config/firejail/firefox.local`. These files don't exist in a default installation, but will be included by the main firefox profile if you create them. Check that you have `include firefox.local` in your `/etc/firejail/firefox.profile`.

For more information about configuring firejail, check out their documentation at https://firejail.wordpress.com/

**Comment by LeonCame** [comment]
> Possibly updated info.
> 
> KeePassXC - 2.6.3 KeePassXC-Browser - 1.7.4 Operating system: Win10 Browser: Firefox
> 
> Sandbox setting -> Resource Access -> Add File/Folder -> Set the path to \Device\NamedPipe\org.keepassxc.KeePassXC.BrowserServer_*
> 
> Then your KeePass Browser extension should work as normal.
> 
> Hope this helps.

Thank you so much !
I confirm that the instructions from xarx00 from August 19, 2018 no longer work, but the instructions from your post work fine!

Latest Waterfox G5.1.2 (64)
Sandboxie Classic 5.6.1.7 (64)
KeepassXC-Browser 1.8.4
KeePass XC 2.7.4
