### ISSUE TITLE
"Fill TOTP" does nothing on right click menu

### ISSUE THREAD

**Issue by brwolfgang** [keepassxreboot/keepassxc-browser#28]
## Expected Behavior
When selecting the option "Fill TOPT" opened by right-clicking a text box the configured TOTP for the current page (Keepassxc entry) should be pasted.

## Current Behavior
When "Fill TOTP" is clicked nothing happens, the textbox is still empty.

## Steps to Reproduce (for bugs)
1. Fill in you user/password using the extension (the keepassxc entry must have TOTP set up)
2. When prompted for a TOTP right click the textbox, -> KeePassXC-Browser -> Fill TOTP
3. Nothing happens even though the current entry has TOTP set up.

## Debug info
No error generated on the console

## General Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Proxy used: NO

**Comment by varjolintu** [comment]
Try the following:
- Create a new attribute to your entry with name `KPH: {TOTP}`
- Put `{TOTP}` to its value

**Comment by brwolfgang** [comment]
It works, but I'm curious why this is necessary since username/password don't need special attributes to be filled in. Any thoughts?

**Comment by varjolintu** [comment]
Because these are advanced string fields, an extra option which also needs extra configuring.

**Comment by vanous** [comment]
This extra configuration is not intuitive and makes TOTP integration, which is otherwise great,  unusable. Nobody will every add 

KPH: {TOTP} {TOTP}

as an extra value to the database. We already have the otp attribute in.
Is there a way around this? 
As for #1652 I may be adding TOTP via another program, like KeePass2, which will not add KPH: {TOTP} automatically, like the #1652 mentions.
thank you
