### ISSUE TITLE
Unable to select password field in some websites

### ISSUE THREAD

**Issue by alvarogmj** [keepassxreboot/keepassxc-browser#292]
For some websites, the "Choose custom credential fields" tool doesn't allow to select a password field.

## Expected Behavior
After the username field is chosen, the tool should allow to select a password field.

## Current Behavior
In some pages (e.g. Monoprice account login), no field can be selected as "password" field

## Possible Solution
I guess it is related to how the input field is created, and I would just want to know what I need to look for in the source in order to find the problem.

## Steps to Reproduce (for bugs)
1. Go to www.monoprice.com/myaccount/myaccount
2. Select "Choose custom credential fields"
3. Select the first field in the Sign In form as "username" field
4. No field can be selected as "password" field

## Debug info
KeePassXC - 2.3.4
keepassxc-browser - 1.2.0
Operating system: MacOS El Capitan
Browser: Chrome, Vivaldi
Proxy used: NO

**Comment by varjolintu** [comment]
The reason for this was that we have a hard coded limit for input fields in a page. This included all the hidden input fields too. The fix ignores all hidden input fields instantly and handles only the "real" ones.

The username field was detected in custom fields because it uses a different search pattern.
