### ISSUE TITLE
Support Pale Moon / Provide .xpi

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [keepassxreboot/keepassxc-browser#321]
Cannot install in Pale Moon, because the firefox addon website blocks installation and there is no .xpi-file available.
## Expected Behavior
I would like to use the keepassxc-browser-addon in Pale Moon and would like to see it on the [Add-On site](http://addons.palemoon.org/extensions/), but would at least expect a .xpi-file to be available from the repo.

## Current Behavior
I cannot install the add-on from the firefox website and there is no .xpi-file to be found in the repo.

## Possible Solution
Either support Pale Moon (that would be great!) or provide the .xpi-file either in the repo or on the website.

## Steps to Reproduce (for bugs)

1. Open the Firefox KeePassXC-Brower [website](https://addons.mozilla.org/de/firefox/addon/keepassxc-browser/) with Pale Moon
2. Note that the addon cannot be installed.

Operating system: Linux Mint 19 Cinnamon
Browser: Pale Moon 28.1.0

**Comment by phoerious** [comment]
We do not support legacy add-ons. Please use a modern browser with web extension support.

**Comment by sergeevabc** [comment]
@phoerious, it seems you confuse _modern_ with _mainstream_. Pale Moon is the [actively][1] developed fork of Firefox ESR 52, which is [valued][2] more and more as time goes by. 

[1]: https://forum.palemoon.org/viewforum.php?f=1
[2]: https://www.reddit.com/r/palemoon/comments/92ce4o/why_i_switched_to_pale_moon_some_time_ago/

**Comment by droidmonkey** [comment]
When pale moon reaches 1% adoption let me know. There is an equal, if not more, retaliation to these forked browsers. And for good reason.

https://www.howtogeek.com/335712/update-why-you-shouldnt-use-waterfox-pale-moon-or-basilisk/

**Comment by sergeevabc** [comment]
@droidmonkey, the article you provided is written by a _columnist_ and not a _developer_, so no wonder it’s full of sloppy observations (“that fork uses outdated code”) leading to rash conclusions (“don’t use it”). It's like saying the libraries should be closed, because they are full of allegedly outdated books (e.g. [Meditations][1] by Marcus Aurelius).

Pale Moon for that matter renders websites in accordance with modern web standards, yet is skeptical about inheriting momentary tech impulses such as e10s, webextensions, webrtc, etc — things not directly related to accessing remote text/images/scripts. This approach can be called conservative, not outdated. Not to mention FF’s bugs which might be neglected for years (because, oh well, “your bug affects 1% of our imaginary users so be patient”, whereas Pale Moon devs fix them almost instantly). 

Anyway, what adoption rate does KeepassXC have? It’s an outsider as well, so why so snobbish toward other outsiders? Take Mega as an example: being not the first cloud service for files one thinks of, they care to provide [extensions][2] both for FF and PM.    

cc: @wolfbeast

[1]: https://www.goodreads.com/book/show/30659.Meditations
[2]: https://mega.nz/extensions

**Comment by phoerious** [comment]
Comparing libraries holding old books to old browsers is a rather lopsided comparison. Better compare it with using an old rusty car without seat belts and an open trunk on the highway at 140mph. Yes, it may work, but boy, I don't want to be in that car.
And believe it or not, I was one of the last to switch from Firefox to Chrome, because I dearly missed quite a few extensions. But most of them were either integrated directly into the browser over time or simply lost relevance in an ever-evolving information age. Today I use Chrome and I don't miss XUL extensions a bit.

**Comment by wolfbeast** [comment]
Since I was cc-ed on this, let me set a few things straight:

- a columnist article from February is going to be inaccurate; we have released a new milestone in August that should give no reason at all to this negative sentiment about web compatibility any longer. The infamous buzz post on mainstream IT media is also very much incorrect and this has been discussed at length in our community.
- If you feel XUL is not a technology to target any longer, then that is your choice; the growing number of applications using the XUL platform as we have been working on since Nov 2017 tell a different story though. http://thereisonlyxul.org
- Since we are talking about extension formats, take note that WebExtensions are much more limited than what is demeaningly called "legacy". Every extension dev knows this. If it happens to provide enough API access for your purpose then that's wonderful, but Pale Moon will not adopt an inferior extension technology that brings with it a lot of hacks and a large sec attack surface (most of the sec vulnerabilities fixed in the latest Firefox release were all directly related to WEs, FYI).

Ultimately, it's your decision what to spend your time on, of course. All of this is just for your information. If you want to limit yourself to Chrome and Google technologies only, then by all means, go ahead and close this issue.

I'll be unsubscribing from this issue after I post this. @sergeevabc please do not CC me on other issues without at least discussing it with me on the forum before doing so. Thanks.

**Comment by sergeevabc** [comment]
> @phoerious
> comparing old books to old browsers is a rather lopsided comparison

Netscape is an old browser for that matters, whereas Pale Moon is a conservative one, meaning it lacks fleeting fashion features, yet renders websites properly and smoothly.


> @droidmonkey 
> a random reddit post that had 12 likes … article I linked to was the top hit

I linked to a first handed sincerely written user report (lots of similar output around), whereas you linked to an article written mostly to place ads around, get the revenue and eventually pay the author, who hardly bothered to ask why the condemned forks risen in the first place.

> @droidmonkey
> the most favorable extension method … that is NOT XUL anymore

Mainstream method is not equal favorable. Long ago lots of users stumbled upon Firefox and still stick to it whatever breaking changes are introduced, because challenging the status quo and exploring terra incognita for alternatives scares the majority. Getting used (along with cursing) to whatever Mozilla Foundation decided to do is considered to be a lesser evil. 

But there is also a minority, thousands of brave people, who either disagree to what happens under FF’s hood or simply don’t get why, out of blue, rendering familiar websites requires more and more CPU/RAM. Obviously, its market share cannot impress, but what really matters it is increasing, not decreasing. It’s like the case with a gradual migration from Gmail and Outlook to zero-knowledge communication providers.

Both parties deserve a better way to manage passwords than a built-in manager offers. Apart from Mega, @gorhill, the developer of uBlock, understands that too, that’s why he cares to provide “legacy” version of his ad-blocker as well. Remember, Pale Moon users (who are generally privacy/security-minded) are already friends of Keepass(XC) and lust for XUL extension, whereas FF’s users are yet to be attracted.

**Comment by gorhill** [comment]
> @gorhill, the developer of uBlock, understands that too, that’s why he cares to provide “legacy” version of his ad-blocker as well.

If you are going to use me and uBO as a pro-argument, I will speak for myself: uBO is [no longer developed for Pale Moon](https://github.com/gorhill/uBlock/commits/firefox-legacy) -- it's [hundreds of commits behind current uBO](https://github.com/gorhill/uBlock/compare/firefox-legacy-1.16.4.5...master). That there is a XPI available does not mean it's being developed, it is by now far behind the webextension version in term of features.
