### ISSUE TITLE
Generating password is visible by default 

### ISSUE THREAD

**Issue by prog-amateur** [keepassxreboot/keepassxc-browser#332]
Hello, when I register in a new website, I can generate password. However, those passwords are visible by default, which is a security issue (over the shoulder spy / screenshot spy). 

Thank you for you help. 

## Expected Behavior
Either I click on the yellow key or the black cube icons to generate a password, those should be hidden by dots. 

## Current Behavior
Either I click on the yellow key or the black cube icons to generate a password, those are visible. 

## Debug Info

KeePassXC - 2.3.4
Revision: 2.3.4 (Flatpak version)

Operating system: Ubuntu
CPU architecture: 64bits

Enabled extensions:
- KeepassXC browser extension for Firefox

**Comment by varjolintu** [comment]
Maybe this could be added behind an option.

**Comment by droidmonkey** [comment]
OK, so you mean the password generator in the application when you are not editing an entry. The password is visible by default there.

**Comment by phoerious** [comment]
That's working as intended. There is a good chance you actually want to see the password there, since you are probably using it for something else than saving it in your password manager and then forget about it. And if you are in a public space, nothing stops you from toggling the visibility and then regenerating the password.

**Comment by amnk** [comment]
I'm not very comfortable with this either. Can it be made configurable?
