### ISSUE TITLE
Allow to add new entry without username

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc-browser#350]
## Expected Behavior
When updating a password on the site, KPXC (browser extension) correctly detects an updated password and flashes red. When opening the extension bubble, allow me to click 'New' to create a new entry. If necessary, open the main KPXC window to allow me to add the username, or have a text field in the extension bubble itself.

## Current Behavior
Upon opening the extension bubble, the 'new' option is greyed out for it didn't detect any username.

Reasoning: I'm currently in a migration process (from browser to KPXC), and add an item whenever I use a service (that I use irregularly). Already logged in to a site I update the password, making use of KPXC's generation mechanism. Currently I have to copy-paste the generated password to the 'new entry' screen of the main KPXC window.

## Debug info
KeePassXC-Browser Version: 1.3.0
KeePassXC Version: 2.3.4
Operating system: Ubuntu 18.04
Browser: Firefox

**Comment by varjolintu** [comment]
Currently the New button is disabled if username is not detected. Probably the page has only the password field, so the extension assumes you are updating the password, not creating a new entry. So instead of updating your entry you are creating a new one?

This could be extended of course, that whenever there is no username set, you could still create a new entry and KeePassXC could ask the username, just like you suggested.

**Comment by keunes** [comment]
Indeed; since it's a password reset page, there's no username field. I would at that point like to create a new entry yes, from the browser 'bubble' (which now is not possible).

> This could be extended of course, that whenever there is no username set, you could still create a new entry and KeePassXC could ask the username

Such extension would be much appreciated :)
