### ISSUE TITLE
You use an old version of KeePassXC.

### ISSUE THREAD

**Issue by k8oi** [keepassxreboot/keepassxc-browser#375]
Turned on my laptop and recieve a notification from the KeePassXC Chrome extention "You use an old version of KeePassXC. Please download the latest version from keepassxc.org"

KeePassXC-Browser Version: 1.3.1
KeePassXC Version: 2.3.4

Don't understand why I'm getting the notification?

I am using v2.3.4...

![keepassxc extention notification](https://user-images.githubusercontent.com/42382915/51034320-66681e80-1574-11e9-9690-107985a071ad.PNG)

![keepassxc version](https://user-images.githubusercontent.com/42382915/51034373-90214580-1574-11e9-8b8f-83fbcc502c7e.PNG)

**Comment by apiraino** [comment]
Same issue here.

The new browser extension has been released and requires KeepaxxXC v2.4.0 (as per their [release notes](https://github.com/keepassxreboot/keepassxc-browser/releases/tag/1.3.1)).

Problem is that KeepassXC 2.4.0 is not yet available on the repositories (I've checked Ubuntu and Debian ones).

This could be improved with a better syncronization between the release of the two applications, since they're often intertwined.

**Comment by EruIluvatar** [comment]
Same here, on KeepassXC-Browser 1.3.1 on Firefox and KeepassXC 2.3.4 on Linux

**Comment by varjolintu** [comment]
The extension does not require 2.4.0. It just has a feature that will be only used when that version is released.

**Comment by janw-me** [comment]
Same here

- KeePassXC-Browser: 1.3.1
- KeePassXC: 2.3.4 
- FF 64.0.2
- Ubuntu

I'll wait patiently.

**Comment by apiraino** [comment]
> The extension does not require 2.4.0. It just has a feature that will be only used when that version is released.

oh I stand corrected, thanks! :+1:

**Comment by flanger001** [comment]
I know this was closed two months ago but I got this today also. I'm on client 2.3.4 and browser 1.3.2. Got excited for a minute because I thought there was a new KeePassXC version out!

**Comment by itspetrus** [comment]
Hello everybody, seem situation over here. Also on client 2.3.4 and browser 1.3.2 on OSX High Sierra and Firefox 65.0.1. Regards, Peter.

**Comment by droidmonkey** [comment]
macOS 2.4.0 will be released on Monday. You can remain excited!

**Comment by noMICROSOFTbuhtz** [comment]
Same problem here on Debian stable. KeePassXC 2.3.4 is the current stable release in the official debian repository. You can not force a Debian user to install something out of the debian repository.
For Debian user it doesn't matter if there is a 2.4.0 available. It need to be integrated into the offical package repository.

Keep this in mind when developing your AddOn. This is currently a bad bug (by design).

What is the technical reason to force 2.4.0?

Reopen this

**Comment by varjolintu** [comment]
@noMICROSOFTbuhtz You don't have to upgrade to 2.4.0. 2.3.4 works just fine with the extension. If you want to get rid of the annoying update message in the popup, set _Check for updates of KeePassXC_ in the Settings page to _never_.

**Comment by stmllr** [comment]
@noMICROSOFTbuhtz 
> Same problem here on Debian stable. KeePassXC 2.3.4 is the current stable release in the official debian repository.

Currently the package is available through [stretch-backports](https://packages.debian.org/stretch-backports/keepassxc) which follows different policy than packages from the stable release:

> Backports cannot be tested as extensively as Debian stable, and backports are provided on an as-is basis, with risk of incompatibilities with other components in Debian stable. Use with care!
https://backports.debian.org/
