### ISSUE TITLE
Network?

### ISSUE THREAD

**Issue by DocMAX** [keepassxreboot/keepassxc-browser#43]
Legacy KeePassHTTP was able to act as "server" through network. Please keep this functionality!

**Comment by phoerious** [comment]
No, it wasn't, unless you tunneled it.

**Comment by phoerious** [comment]
The new API provides stronger security, because it only allows one specific application to talk to the browser instead of every application that is running on the system (including those of other users). The old API was also based on a buggy HTTP server implementation which we want to get rid of. If you really can't use KeePassXC locally, use a custom keepassxc_proxy, which tunnels STDIO through an SSH socket.

**Comment by DocMAX** [comment]
I install KeePassXC on server to serve all my clients. Please add a (secure) client-server model to your tool. Thx for the keepassxc_proxy hint.

**Comment by DocMAX** [comment]
Can you please guide me how to make a remote connection to keepassxc "server" with keepassxc_proxy. I dont understand. I would also like to see the Firefox plugin connection to the server on my Android device. Thanks.

**Comment by varjolintu** [comment]
If you want to use that kind of custom connection to your Android device you can still use the KeePassHTTP-Connector or similar.

Remote connection with KeePassXC would need you to build a custom proxy that does something like: KeePassXC <-> Custom Proxy <-> Your server etc <-> Custom Proxy <-> KeePassXC-Browser.

**Comment by DocMAX** [comment]
What do you mean with "Custom Proxy"? Do i have to alter code and compile?

**Comment by varjolintu** [comment]
Yes. You have to do it by yourself. Alter the code or make one from the scratch. Any language will do.
