### ISSUE TITLE
Raising awareness around the security concerns of auto-fill 

### ISSUE THREAD

**Issue by i38** [keepassxreboot/keepassxc-browser#437]
Autofill functionality brings with it dangers, where an abuse of an XSS vulnerability or malicious advert could also potentially lead to your credentials being stolen. For this reason, a warning exists in the settings to discourage the use of unsafe functionality:

> ### Automatically fill in single-credential entries.
> Let KeePassXC-Browser automatically fill in credentials if it receives only a single entry.
> **Warning! Using auto-fill is not safe. Use at your own risk.**

There are however no warnings around an equally dangerous option:

> ### Activate autocomplete for username fields.
> Show a dropdown list containing available credentials for all username fields on a page.
 
## Current Behavior
With the option "Activate autocomplete for username fields" enabled, when a user clicks the username field it creates a dropdown like so:

![image](https://user-images.githubusercontent.com/48587738/54427814-7ab2ce00-4713-11e9-9034-38e113fb22a7.png)

At this point, user interaction is not required to fill in the credentials as the dropdown can instead be "clicked" with javascript, and the credentials then stolen like in any other autofill attack. 

## Possible Solution
A warning could be present to discourage the use of the option:

> ### Activate autocomplete for username fields.
> Show a dropdown list containing available credentials for all username fields on a page.
> **Warning! Using auto-fill is not safe. Use at your own risk.**

A technical solution would be preferable, however I am unaware of how to achieve this. Currently, as the dropdown is part of the DOM, you can interact with it with javascript. In order to address this technically, I believe that the dropdown would need to be moved outside of the DOM.

**Comment by varjolintu** [comment]
Abusing this is possible only if credentials are received automatically and always accepted (user has chosen Allow with the remember option). And many are using the extension exactly this way, so it can be a problem, yes.

I can think a few ways the security can be improved:
- `Event.isTrusted` must be used to confirm a manual action has been used before filling anything:  [https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted)
- The added elements use random ID's and names. Not so effective after all because scripts can check if some code has been added to the page.
- Move the dropdown outside of the DOM (how?).

If you wish not to use autocomplete at all, you can disable it from the settings, and then use the popup or keyboard shortcuts for filling. Anyone concerned about this should not remember the Allow setting when retrieving credentials.

**Comment by droidmonkey** [comment]
This is precisely why the default arrangement for KeePassXC is to NOT have all your database information sent to the browser by default.

**Comment by i38** [comment]
@droidmonkey I will send you an email now with an example. I was refraining from posting the details publicly as I am cautious about making it too easy for script kiddies.

**Comment by i38** [comment]
If 'Event.isTrusted' is trusted, that seems like it would be very effective at preventing this in the supported browsers.

I am not so much a fan on relying on random names as I feel like this will be easily bypassable. 

Personally, I have opted for having to click on the KeePassXC extension and selecting my suggested credentials as I believe that this is easy to use but limits autofill attacks (unless the malicious scripts are on a login page) without losing the benefit of phishing protection (am I on the right domain).

**Comment by droidmonkey** [comment]
Received. We'll see what we can do to prevent the attack vector.

**Comment by varjolintu** [comment]
Adding check for `Event.isTrusted` no longer allows the script to even open the Autocomplete menu, or selecting credentials from the list even if it's opened manually.
