### ISSUE TITLE
credentials input/output problem

### ISSUE THREAD

**Issue by gthb1** [keepassxreboot/keepassxc-browser#470]
Hi,
While KeePassXC is generally great, I have some problems:
#1 Cannot get it to work in FF51dev, using KeePassXC-Browser 1.3.3.
#2 In FF66.0.3 it does not offer credentials when trying to login to Gmail.
#3 Cannot save any credentials in any browser, from any login screen, into KeePassXC.
Please advise.
Thank you!

**Comment by omega3** [comment]
I set enable Username-only Detection
https://imgur.com/SVzI0l4

I can see my login name 
https://imgur.com/pOPqEFr

but when I click next the data are wrong
https://imgur.com/NWjXupo

When I want to set non-standard login fields extension doesn't alow me to do it, I mean go to the next step, because I cannot click next on gmail login site, because extension acts like active window and below is inactive.  
https://imgur.com/Csn6Bwf

And this may happen on different sites. 

Wouldn't it be a good solution to temporarily "deactivate" choose next field and allow user to go to the next step (next site)  and than activate choose option and choose proper field?

**Comment by varjolintu** [comment]
@omega3 Non-standard fields are not supported, with `username` type as an only exception. For the Google page, you don't have to set any custom fields.

For the username only detection, setting the URL to `https://accounts.google.com/*` is enough.

I'm not sure what you mean by "deactivating" choosing the next field.

**Comment by omega3** [comment]
I did `https://accounts.google.com/*` but nothing changed. 

> I'm not sure what you mean by "deactivating" choosing the next field.
When I am at this stage:
https://imgur.com/Csn6Bwf
I cannot press next on gmail site to proceed to choose password field, because on gmail login site there is only one field.

Maybe I do something wrong but:
first stage at gmail is choose user name field
https://imgur.com/qIIEQeb
I press field and the next step is choose now password field 
but in the green area I still have headline "user name".

**Comment by varjolintu** [comment]
You don't need to set the login field as a Custom Field. If you have enabled Username-only detection for the page, it's enough.

I'm still not sure what you mean by wrong data. When you have entered your email address, the next page will show the password field. Autocomplete on that field will show you your username (not the password), and it will fill the password instead.

**Comment by varjolintu** [comment]
Please reopen the issue if the problem still persists.
