### ISSUE TITLE
Enabling the extension in Firefox breaks Facebook Messenger conversation list

### ISSUE THREAD

**Issue by sliwowitz** [keepassxreboot/keepassxc-browser#481]
Facebook Messenger web interface https://www.facebook.com/messages/ won't show the conversation list in the left pane when KeePassXC-browser extension is enabled.

## Expected Behavior
The KeePassXC extension doesn't interfere with the converation list pane on the page in any way.

## Current Behavior
The conversation list on the left pane shows "Could not display conversation list." Blacklisting facebook in KeePassXC extension settings does not help. Disabling the extension gets the functionality back. This happens regardless on whether the KeePassXC desktop app is running/connected or not.

## Steps to Reproduce (for bugs)
1. Start Firefox form a clean profile
2. Install the KeePassXC extension
3. Go to https://www.facebook.com/messages/ and log in
4. The left pane that should show a list of contacts/conversations is blank and shows "Could not display conversation list."

## Debug info
KeePassXC - 2.4.1 (2.4.1-1ppa1~disco1 from the PPA)
KeePassXC-Browser - 1.4.0 (from the Mozilla add-ons site)
Operating system: Linux x86_64 - Ubuntu 19.04
Browser: Mozilla Firefox 66.0.3 (form Ubuntu repos)

### Extension disabled - facebook messenger works: 
![Screenshot from 2019-04-22 11-54-09](https://user-images.githubusercontent.com/5609862/56495427-fdd6f900-64f5-11e9-8717-4c40b37eb282.png)
### Extension enabled - facebook messenger doesn't work: 
![Screenshot from 2019-04-22 11-54-18](https://user-images.githubusercontent.com/5609862/56495428-fe6f8f80-64f5-11e9-8cff-9297367b5ff8.png)

**Comment by Chronoes** [comment]
I would like to add to this issue. I experience the same problem when reproducing the steps but the error message in the console is a bit mangled by Facebook
```
ErrorUtils caught an error: "<![EX[["caught error in module MessengerMasterView from %s: %s","Error","Perm...". Subsequent errors won't be logged; see https://fburl.com/debugjs.
```
I cannot tell what the real error message is but it seems it is similar to this:
```
Error: Permission denied to access property "apply"
```

I've so far encountered this problem on Imgur where it fails to load a selected album on my uploaded images and Mega.nz where download never starts. Disabling the extension does not produce this error and works as expected. The stack traces for those sites are unrelated but I suppose it's related to `Function.prototype.apply` method in some way.

**Comment by droidmonkey** [comment]
We must be overwriting a method that is defined by these other sites.

**Comment by varjolintu** [comment]
Tested this quickly with Chromium and it's not affected.

**Comment by linkp** [comment]
I am encountering a similar issue in my company helpdesk on a submit button in a field which adds a note or sends an email from a ticket.

Browser is Firefox 66.0.3 on Ubuntu 16.04.6 LTS
Extension version 1.4.0
KeePassXC 2.4.1 AppImage

Expectation: Click button and a a note is added or an email is sent
Reality: Nothing happens. Browser console reports: Error: Permission denied to access property "apply"

I had initially encountered the problem after installing the PassPortal Ocular addon which is also a password manger plugin. I was able to get the form to function by disabling that extension and reloading the page. I then started encountering the same symptom even with the Ocular extension disabled. Testing through isolation identified the recently installed KeePassXC extension as the cause. I installed the KeePassXC addon after the Ocular addon. When either extension is enabled, the result is the same.

I ran into the same problem with the Ocular and some forms in Suite CRM. If the underlying cause is the same, the KeePassXC addon may cause the same disruption in that package as well.

**Comment by Fumble** [comment]
I have the same issue on all dropdowns of an other site (zestedesavoir.com): same error " Error: Permission denied to access property "apply"" when I click on a dropdown.

Reproduced on;

- Windows 10 + Firefox 66.0.3 + KeepassXC 2.4.1 + extension 1.4.0
- Manjaro Linux + Firefox 66.0.3 + KeepassXC 2.4.0 + extension 1.4.0
