### ISSUE TITLE
Support username-only login forms

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc-browser#514]
## Expected Behavior

Popular sites with multi-part login forms should be automatically supported by the plugin. On a recognized (or registered in settings) multi-part form, when pressing the "Fill Username+Password" keyboard shortcut the username field will be filled in.

## Current Behavior

Multi-part form sites need to be manually registered in settings. Pressing the fill username+password keyboard shortcut does not work reliably.

## Possible Solution

1. Include a whitelist of popular websites that use multi-part login forms
2. Fix the use of "Fill Username+Password" keyboard shortcut on multi-part login forms

**Comment by droidmonkey** [comment]
Related to #159 and #513

**Comment by AdamPS** [comment]
Thanks @droidmonkey.  I feel that each solution has benefits in different cases and it doesn't necessarily have to be a choice - we could have both.

1. Whitelist could work well for users with just a few passwords on main sites.  However it will never solve all websites.  It will tend to go out of date.  It's not safe to whitelist an entire site because there will be other pages on the site with input fields that are not usernames so the whitelist would need to be page by page.
2. This fix is perfect for people who use the keyboard shortcut and works in all cases.

I will donate for option 2.  Is there any official way of posting bounties?

**Comment by droidmonkey** [comment]
Yes you can post a bounty to: https://www.bountysource.com/issues/73452930-support-username-only-login-forms

**Comment by AdamPS** [comment]
OK, I posted a bounty.  The bounty applies to solution 2 and not to solution 1.  Thanks!

**Comment by varjolintu** [comment]
@AdamPS See https://github.com/keepassxreboot/keepassxc-browser/pull/520.

**Comment by varjolintu** [comment]
The whitelist would only affect to usage of autocomplete menu. Using a keyboard shortcut triggers it if there are multiple credentials. While the current release doesn't work perfectly with it #512 will fix the behaviour.

**Comment by AdamPS** [comment]
@varjolintu I have just tested and it works perfectly in the latest release many thanks.  The bounty is yours.  Do we need to close this issue to trigger it?

**Comment by droidmonkey** [comment]
Yes

**Comment by AdamPS** [comment]
Thanks. Looks like the bounty is ready for you to claim. Let me know if you have any difficulty.

**Comment by varjolintu** [comment]
Glad to hear it works!
