### ISSUE TITLE
Allow skipping of auto-submit

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc-browser#542]
When browser extension settings -> Auto-submit login forms is enabled then pressing AS+U fills the form and submits.  This is great 99% of the time, but for a few websites KeePassXC browser extension cannot fill the field - for example when the website asks for specific characters ("pickchars"), or the website randomly pick one of several possible security questions.

For those websites I would like KeePassXC to fill the fields it can, but _not_ submit.  The input focus should be left in the first empty password field (or failing that in a non-empty one) ready for me to type the extra data.

## Expected Behavior
There should be a way to skip auto-submit for a specific site.

## Current Behavior
You have to alter the setting temporarily which is slow: open settings; temporarily disable auto-complete; press AS+U; fill the extra fields by hand; submit; open settings; enable auto-complete.

You could also try entering the extra data first, then pressing AS+U.  However I have at least one example site where it forces you to fill something in the main password before you can type in the pick chars so order can matter.

## Possible Solution
2 alternatives I can see:
1) Allow storing an exception to auto-submit for a specific site.
2) Provide a separate key-press for fill and fill+submit.

**Comment by varjolintu** [comment]
Adding a separate kayboard shortcut will be a little problematic because both Chromium and Firefox has restricted the maximum amount of them to four. All of those are already in use.

**Comment by AdamPS** [comment]
So we can store an exception.

We should store it as additional attribute or property in the database entry please.  The problem with the "Site preferences" in the browser settings is that I have to enter the same information over and over again for each browser on each device - and as a web developer I use a lot of different ones!!

I have added a bounty https://www.bountysource.com/issues/74091841-allow-skipping-of-auto-submit.  It is intended for the solution described in this comment.  Thanks!

**Comment by varjolintu** [comment]
One feature that's still missing (with Site Preferences) would solve this: storing the extension's settings to the connected database. If automatic, those are loaded on every database unlock and stored after every change. This is related to https://github.com/keepassxreboot/keepassxc-browser/issues/377.

One complex issue is that some of the options would have to be "global" and stored to the extension itself without the need to add them manually to every database.

Need to think this over.

**Comment by ba32107** [comment]
@AdamPS I took a look at the code and I think I can tackle this issue. I like your suggestion:
- Add an extra field to the entry metadata (on the 'Advanced' tab), called 'Do not auto-submit entry in the browser' (or something similar)
- Check this field in the browser extension, and if enabled, do not auto-submit (but fill out the form)

Does this sound good? You also mentioned custom login fields. How do those fit into the picture?

**Comment by droidmonkey** [comment]
Use the custom data of the entry, not the attributes.

**Comment by ba32107** [comment]
Of course, I meant it as a separate data field, but it makes sense to put it on the advanced tab. I'll post a screenshot once done.

**Comment by varjolintu** [comment]
@ba32107 That is not going to solve the problem if we want to ingore Auto-Submit for a certain **site**. Adding and extra data to entry custom data only applies for that entry, not the whole site. The user would have to add the same data for each entry for that site. And what if the URL of the entry changes?

**Comment by ba32107** [comment]
This is an interesting question. Yes, in this case the user would need to set this for each entry for that site. The alternative would be to have an exception list in the database settings. There is already a browser-integration tab (where you enable the integration itself). We could have an URL exception list here, called "Skip auto-submit on the below URLs", or similar. Then, if an entry's URL matches one of the exceptions, the form wouldn't be auto-submitted.

However, I am not sure that this is the most intuitive solution. As @AdamPS mentioned, in my mind this setting is related to the entry itself - I would naturally look for this option in the entry properties, and not the global database settings. But since the bounty was posted by @AdamPS, I'd be interested to know his opinion.

What do you mean by URL changes? I don't see an issue there. The URL only determines whether or not an entry matches or not. The auto-submit happens after the match/no match decision has been made. If a URL changes, we won't even get to the point of the auto-submit.

**Comment by varjolintu** [comment]
In my opinion, I would do the following:
- Extend the Site Preferences settings with "Ignore Auto-Submit" option
- Add a feature to the extension that supports both browser sync (Firefox or Google Account) and manual importing/exporting the settings

This would ensure the option to be site specific, and it will not add any extra data to the database or any of its entries. The whole Auto-Submit thing is only relevant in the extension, so it would make sense to implement the option to the extension, and leave KeePassXC side untouched.

**Comment by ba32107** [comment]
I can't find any setting in the browser extension for sync or import/export. Is that a different extension?

**Comment by varjolintu** [comment]
@ba32107 No. As I said in the previous message, that feature must be added to the extension. Currently it doesn't have it.

**Comment by ba32107** [comment]
I see - I assumed so, but to me it wasn't obvious from your message. However I think these two are two different features, and should be tackled in separate issues. 

The combination of these two features would solve @AdamPS's problem - furthermore, the first (smaller) improvement would allow him partly solve the problem, and whenever the sync is ready, we can consider it fully solved.

Adam - what do you think?

**Comment by AdamPS** [comment]
@ba32107 thanks for responding to my bounty and sorry for the slow reply as I was away.

I'm not sure about sync - I added a comment on #377 to explain why.

In my opinion "skip sync" is a setting on the database entry which indicates that the entry is incomplete.  It could be that KeePassXC cannot fill in the other fields ("pick chars") or that the user prefers to manually fill in the other fields for added security.

Putting the setting on a site/URL is less correct.  A database entry could in future apply to multiple URLs.  Multiple entries for a single URL could be different - a highly-sensitive login is incomplete so needs skip auto-submit, but a secondary "test account" can auto-submit.

> The whole Auto-Submit thing is only relevant in the extension, so it would make sense to implement the option to the extension, and leave KeePassXC side untouched.
I agree with that.  I suggested that the data should be stored in the database entry.  However the interface and code can be in the extension, which can write a custom attribute/plugin data without any changes to KeePassXC.

**Comment by varjolintu** [comment]
Thank you for the ideas. It seems the entry custom data might be the best solution for this after all.

**Comment by ba32107** [comment]
@AdamPS Oh I see what you mean: what you recommend is that you would like to set this in the extension itself? So from a usability perspective, you would like to be able to enable the 'Do not auto submit' for a _specific entry_ in the extension settings page?

I agree that this makes sense - this data is specific to the browser extension and a user would naturally look for this option on the extension settings page. Under the hood, it can be stored on the entry data.

However this will need some planning, because the setting currently doesn't have any setting page for _entries_. It only has a general settings page, and a site preferences page, but nothing that would set things on the entry itself - this would be the first one. We need to think about how this would fit in the overall picture and the long-term plans of the extension.

The simpler solution is what I described in https://github.com/keepassxreboot/keepassxc-browser/issues/542#issuecomment-506962478. You'd be able to set this in KeePassXC (not the extension), but it would behave the way you expect it. This I can code fairly quickly and confident I can do - the solution I described above needs some more planning and thinking.

**Comment by AdamPS** [comment]
Balazs I see what you mean.  The simpler solution is good, but @droidmonkey responded with a good point:

> Use the custom data of the entry, not the attributes.

We could alter your suggestion so that the extensions looks for a new custom data "no auto-submit".  The difficulty is that there is no way I can see to manually add custom data.  So it comes back to the question of where to put the setting in the extension GUI.

How about adding a checkbox on the popup window used to save a password?  This window has a title "Username or password changed! Save it?"  That seems fairly easy to code - what do you think?  Of course it would be better to be able to edit an entry without having to resave the credentials, but we could do that later in a separate issue.

**Comment by droidmonkey** [comment]
I see a future where we have a browser integration tab in the entry edit view that lets you customize various advanced settings for each entry.

**Comment by ba32107** [comment]
Yes, I pictured it exactly as @droidmonkey described it. You'd be able to set this on the entry metadata, in KeePassXC.

@AdamPS you're right, there's no way currently to add custom data, but I can build some. It's just much easier and faster to do it in KeePassXC. If we need to put it in the extension, then we'll need to think about how that should work - as you rightly described, one possibility is to use the existing popup, but then we would be re-saving the entry each time - not the best solution from an implementation point of view.

I think that we should only go with putting the setting in the extension if the long term plans indicate that that is the direction we want to move. @droidmonkey's comment makes me think otherwise - however, I'm not one to decide this :)

**Comment by AdamPS** [comment]
OK it sounds good to me.  So as I understand it, the solution has two parts:

1) The browser extension checks for a new plug-in data item "skip auto-submit" and if found then skip auto-submit.  In that case, the cursor should be in first empty password field ready for the user to type in the missing information.  If there is no empty password field, put the cursor at the end of the first password field.

2) In KeePassXC, add a way to set the new plug-in data item using a new "browser integration" tab.

I am very happy with this solution it definitely will get the bounty.

**Comment by droidmonkey** [comment]
You can put it in both the extension and my future vision. They are compatible with each other.

**Comment by ba32107** [comment]
@AdamPS yes, this is how I pictured it. Sounds good then! :) I will posts updates once I have some.

**Comment by varjolintu** [comment]
The following PR's have been opened that adds support for this:
https://github.com/keepassxreboot/keepassxc-browser/pull/592
https://github.com/keepassxreboot/keepassxc/pull/3444

**Comment by AdamPS** [comment]
@varjolintu great news, many thanks

I haven't learnt how to build for myself so I will wait until a new release and try it then.

**Comment by varjolintu** [comment]
@AdamPS I'll notify you when there's a snapshot build available with that feature, so there would be still time to make some modifications if necessary.

**Comment by AdamPS** [comment]
Great thanks.

**Comment by ba32107** [comment]
Sorry Adam for being quiet for the past few weeks, I haven't had time to work on this. Glad to see progress has been made.

**Comment by AdamPS** [comment]
@varjolintu any update?  I am keen to try your new patch.

**Comment by varjolintu** [comment]
@AdamPS The extension already supports it, but KeePassXC side haven't merged the changes yet. For now, only way to test it is to download the branch https://github.com/varjolintu/keepassxc/tree/feature/browser_integration_entry_settings and test it manually.

**Comment by AdamPS** [comment]
Thanks I will keep waiting and hoping as I haven't set up my own build system

**Comment by varjolintu** [comment]
Closing this as the changes are already in the KeePassXC snapshot release.

**Comment by AdamPS** [comment]
Many thanks @varjolintu it works very well
