### ISSUE TITLE
Existing database connection suddenly failing

### ISSUE THREAD

**Issue by OhiraKyou** [keepassxreboot/keepassxc-browser#572]
## Expected Behavior

KeePassXC-Browser consistently connects to KeePassXC.

## Current Behavior

The KeePassXC-Browser extension suddenly stopped recognizing its connection to the KeePassXC application. Possibly related to #370.

After connecting to the KeePassXC application, the browser extension worked fine for a day and half, even after reopening Firefox and KeePassXC. However, now, when I click the extension's icon in the browser, it says "KeePassXC-Browser has not been configured. Press the connect button to pair with KeePassXC." This started happening not long after cloning an entry with user and password references.

Browser integration is enabled for Firefox in KeePassXC's settings. The identifier and eight characters not hidden at the start of the key in the extension settings match those listed in the database settings.

This is the console log after opening Firefox with KeePassXC already running and clicking the extension icon:
```
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:993:13
Server public key: ZG9xobseqKfhLNg0xrLFzqVw4xeCUyFVjiJia+dJKEM= keepass.js:622:25
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:490:25
Error 11: No saved databases found. keepass.js:1078:13
Promise resolved after context unloaded
inject.js:68
    update moz-extension://2069f187-2feb-454a-a2fb-b14c84470b07/data/content_script/inject.js:68
```

The proxy application is enabled in KeePassXC's settings. Other issues mentioned checking if it's already running. While I can't find it in Task Manager, running the proxy executable in KeePassXC's install directory causes it to be listed in Task Manager with a (2).

"Automatically reconnect to KeePassXC" is not enabled in the extension's settings.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.6
Operating system: Windows 10 (64-bit)
Browser: Firefox 67.0.4 (64-bit)

**Comment by varjolintu** [comment]
If you are familiar with debugging extensions, could you provide some more information?

With Firefox it goes like this:
- Go to `about:debugging` and check `Enable add-on debugging`. Then debug KeePassXC-Browser.
- Go to the `Debugger` tab and search `keepass.js` from the file tree under `background`.
- Put a breakpoint inside function `keepass.getCryptoKey()`, starting from line 1090.
- When the breakpoint hits when you click the extension icon, check out the values of `keepass.databaseHash` and values inside the `keepass.keyRing` and see if they match.

**Comment by OhiraKyou** [comment]
It never gets that far; it doesn't pause at the breakpoint. However, a breakpoint in the following function (at [L816](https://github.com/keepassxreboot/keepassxc-browser/blob/0399c63f69d7e5d91b2ed0a4313dae61bce5b155/keepassxc-browser/background/keepass.js#L816)) does pause:
browserAction.js > `browserAction.showDefault` >`keepass.isConfigured`

The `then` body of `browserAction.showDefault` is never entered (the assumption being that `isConfigured` returns false) at [L79](https://github.com/keepassxreboot/keepassxc-browser/blob/0399c63f69d7e5d91b2ed0a4313dae61bce5b155/keepassxc-browser/background/browserAction.js#L79).

The `keepass.isConfigured` function gets to [L822](https://github.com/keepassxreboot/keepassxc-browser/blob/0399c63f69d7e5d91b2ed0a4313dae61bce5b155/keepassxc-browser/background/keepass.js#L822).

Ultimately, the message "No saved databases found." is logged in event.js > `kpxcEvent.showStatus` ([L94](https://github.com/keepassxreboot/keepassxc-browser/blob/0399c63f69d7e5d91b2ed0a4313dae61bce5b155/keepassxc-browser/background/event.js#L94)).

**Comment by varjolintu** [comment]
Hmm. Try adding a breakpoint to [L423](https://github.com/keepassxreboot/keepassxc-browser/blob/0399c63f69d7e5d91b2ed0a4313dae61bce5b155/keepassxc-browser/background/keepass.js#L423) and see where the function returns. That function is the key for checking if the association already exists.

`browserAction.showDefault()` shouldn't affect to anything else that showing extra marks with the extension icon.

**Comment by OhiraKyou** [comment]
That function returns false at [L456](https://github.com/keepassxreboot/keepassxc-browser/blob/0399c63f69d7e5d91b2ed0a4313dae61bce5b155/keepassxc-browser/background/keepass.js#L456).
And, the callback immediately preceding the return (event.js > kpxcEvent.onGetStatus) returns at [L141](https://github.com/keepassxreboot/keepassxc-browser/blob/0399c63f69d7e5d91b2ed0a4313dae61bce5b155/keepassxc-browser/background/event.js#L141).

**Comment by varjolintu** [comment]
Yes, and it returns false because it cannot retrieve the ID from `keepass.getCryptoKey()`. And it still doesn't hit a breakpoint inside it? You said it doesn't get that far.

**Comment by OhiraKyou** [comment]
Ah, sorry. You said "starting from line 1090", and a breakpoint placed there is never reached due to the return caused by the mismatch. Placing one at [L1085](https://github.com/keepassxreboot/keepassxc-browser/blob/0399c63f69d7e5d91b2ed0a4313dae61bce5b155/keepassxc-browser/background/keepass.js#L1085) reveals that the databaseHash and keyRing hash do not match.

**Comment by OhiraKyou** [comment]
Hmm, why does the extension even store and compare this additional database information? This seems like something that should be exclusively covered by the association key created when connecting the extension to the application for the first time. I haven't taken the time to actually understand what's going on behind the scenes, but it sticks out as redundant and a potential point of failure at first glance, at least to me, as a casual observer.

**Comment by varjolintu** [comment]
This whole operation is done because we don't want to give a free access to every application that could connect to KeePassXC using this protocol. That's why every client connecting to KeePassXC must have an ID to pair with. After a client has been associated, the comparison to the existing ID is made whenever necessary. This includes situations where database is switched to another one on-the-fly. That is the reason why the comparison is made quite often in the code.

Behind the scenes, the first public key used when making the first connection and association is used as a connection ID. But for every connection with KeePassXC, a new keypair is created. Still, the connection ID is compared to the one that's used in the association phase.

So for some reason, even when the association has been successful, something happens when storing the information to the local storage of the extension. Sometimes it's a third party application removing necessary information from the browser. But that's not the case in this, because as you told, the connection ID can be seen from the extension settings.

**Comment by OhiraKyou** [comment]
Hmm, I didn't quite understand that. At a glance, it seems the association ID/key should be what is used to associate the extension and the application/database. But, keepass.databaseHash and the keyRing's hashes are used to define the association rather than the ID that explicitly exists to define the association. It just seems weird to associate the two in any other way than their association ID/key.

Again, I don't really know what's going on. But, on the surface level, it just seems unintuitive.

**Comment by varjolintu** [comment]
Could you check what happens inside the function? Does your database hash correspond to the one inside the `keepass.keyRing`, and the connection ID's also match?

**Comment by OhiraKyou** [comment]
As I mentioned in [this reply](https://github.com/keepassxreboot/keepassxc-browser/issues/572#issuecomment-506785581), the databaseHash and keyRing hash do not match. The keyRing's id and key, however, are correct; they match what is shown in the extension and application's settings.

And, that's why I find it weird that the hash comparison is even a thing. The id and key define the association, but they're not actually being used to associate the two. I would have expected the id to be used to get the key. But, some hash is being used to get them both instead.

**Comment by varjolintu** [comment]
Hash comparison must be made because a single connection ID is tied to a certain database, using the hash. `keyRing` lists the database hashes and those entries contain the connection ID.

As you said, the databaseHash does not match. Currently it's calculated with Root group UUID and Recycle Bin UUID added to it. Then it's hashed with SHA256. Is it possible that you've removed the recycle bin from your database or created a new one? I agree it's not the best possible solution to include recycle bin UUID to the hash, but removing it now could cause all existing hashes from all users to fail comparison.

**Comment by OhiraKyou** [comment]
Ah, yes. This did start some time after deleting an entry, causing the recycling bin's automatic creation. Association definitely shouldn't depend on contents.

As for the database hash situation, as a whole, I'd like to propose a paradigm shift that I would consider a significant improvement: since the extension isn't the source of the data, it should act exclusively as a client that sends requests to get or modify data. The extension should not know that a specific database exists. Indeed, it shouldn't even assume that the data comes from a KeePass database file. Rather, it should simply request data or modifications from the connected application and let that application act on those requests however it sees fit. In other words, as a client, it should act like a client.

As a bonus, if designed well, this could allow the browser extension to be used with database applications that use entirely different data storage formats. The client would be format-agnostic, decoupled from the assumptions underlying specific data storage implementations. The only thing coupling an extension to an application (or application's plugin) should be the connection method (association id and key), the commands to receive, and the format in which to respond to those commands. Although, an application should be allowed to ignore commands, in case it doesn't support a specific feature.

Regarding fixing this specific issue on the user end, I assume deleting the association from the extension and application and then reconnecting it would work. I postponed doing that so that we could debug this while the issue was present. But, it sounds likely that we now know the cause and can fix it that way. So, if you don't need any other information while it's still broken, I'll go ahead and recreate the connection and report back.

**Comment by varjolintu** [comment]
We need to modify the Browser Integration not to use any of Recycle Bin data, because it can be moved, deleted and altered. While this can cause existing connections to be invalid, it's the right way to proceed.

The other things you suggested, I don't agree on. Using this extension outside of KeePassXC's context is out of the scope, and there's no need for such features. While I undestand that it would be nice to have a simpler way to do associations from the client, the current implementation is quite secure. We don't want to open the Browser Integration protocol to any clients that could operate with your database freely. If the extension is paired with a certain database, the extension must confirm it is used only with that database, not any database that happens to have a similar connection ID (although the custom data cannot be altered at this point).

The extension must know the database hash (and have a knowledge of a database or databases) so switching between them can be supported. If there's no such data, no hashes, not even a guarantee that the data comes from KeePassXC, how can you ensure with what you are communicating with?

The current protocol implementation can be used freely, and it's possible to create an application that also communicates with the extension, but we are not going to alter the scope of the extension, which main task is: to communicate with KeePassXC.

**Comment by OhiraKyou** [comment]
Alright. Well, I deleted the association and reconnected without issue. So, this mystery is solved. Thanks.
