### ISSUE TITLE
Generate random passwords for password changes and new passwords

### ISSUE THREAD

**Issue by Clindbergh** [keepassxreboot/keepassxc-browser#649]
## Expected Behavior

When visiting an account profile page or a registration page, I wish to generate a new random password with the addon.

Additionally the 'password change' popup when manually changing a password does not appear reliably. Sometimes when a password is changed the popup to update or create a new password does not appear. It would be preferred to be able to trigger the change or addition of the password _before_ submitting the website, so I will not have an unlucky surprise when it did not work.

## Current Behavior

Passwords for new registrations and changes have to be typed manually.

A popup _sometimes_ appears when a password is changed or newly registered allowing to create a new database entry. It does not work when the database is accidentally locked, the connection accidentally dropped or the browser extension did not pick up the password change.

## Possible Solution

An 'add new' button in the extension that creates a new entry using a random password for the current URL and a 'change password' in the extension that changes an existing password.

Or simpler: A button to generate a random password to be filled directly in the password box.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.3
Operating system: Win
Browser: Firefox

## Related

#184 #485

**Comment by varjolintu** [comment]
There's no such popup anymore. It has been replaced with Credential Banner that appears on the top of the page. You can trigger the behaviour using the context menu and selecting _Save credentials_.

The banner does not appear if database is locked, because you cannot save to a locked database.

The password generator still exists, even if its icon is disabled by default. You can either enable using the password icons from the extension's settings, or use the context menu and select _Show Password Penerator_.
