### ISSUE TITLE
Amazon Not Working with KeePassXC

### ISSUE THREAD

**Issue by faxotherapy** [keepassxreboot/keepassxc-browser#691]
KeePassXC does not remember field selection on Amazon login page. I “Choose custom login fields for this page,” and it works fine, but once done and re-connecting to Amazon later, I have to repeat the procedure, which makes me think I'd better manually copy and paste my login name and password…

## Expected Behavior
I expext the plug-in to remember what fields I have selected after using the “Choose custom login fields for this page.”

KeePassXC does remember field selection for some other accounts I have, but with Amazon, it does not work.

## Current Behavior

Add-on does not remember field selection. It does select fields and associate them with KeePassXC, but later, when reconnecting to the site I have to select the fields again.

## Possible Solution
❓ 

## Steps to Reproduce

Try to force add-on to remember field selection.

## Context
❓ 

## Debug Info

```
KeePassXC - Version 2.5.1
Révision : 0fd8836

Qt 5.13.1
Le mode débogage est désactivé.

Système d’exploitation : macOS Mojave (10.14)
Architecture de l'unité centrale : x86_64
Noyau : darwin 18.7.0

Extensions activées :
- Saisie automatique
- Intégration aux navigateurs
- Agent SSH
- KeeShare (partage signé et non signé)
- YubiKey
- TouchID

Bibliothèques cryptographiques :
 libgcrypt 1.8.5
```

Libraries:
- LIBS ❓ 

Operating system: MacOS Mojave
CPU architecture: INTEL
Kernel:
```
$ uname -a
Darwin MBP.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

Enabled extensions:
(I've got tons of them. Do I have to really list them all? Do you know a way how to export extension list to text?)

**Comment by varjolintu** [comment]
Can I ask why do you need to use the Custom Fields at all? If you wish to use the logins divided to two pages, you can open the extension settings, Site Preferences tab, and add the Amazon site to the list: `https://www.amazon.com/ap/*` and enable the "Username-only detection".

**Comment by kekukui** [comment]
> **_you can open the extension settings, Site Preferences tab, and add the Amazon site to the list_**
__________________________
When I press the button for `Add username-only option`, it is added to site preferences...


![image](https://user-images.githubusercontent.com/20834957/71316683-abadf500-2441-11ea-9528-ccc5482f22c1.png)

...but there is no confirmation dialog, and it appears to the casual user that nothing happened, because the Keepass icon does not appear in the Amazon e-mail field.  When I right-click on the e-mail field and select `KeepassXC / Fill Username`, it works -- but there is no visual indication that the Keepass extension has detected this field.

![Keepass Amazon sign in](https://user-images.githubusercontent.com/20834957/71316671-73a6b200-2441-11ea-8895-394ae19991b1.PNG)

However, it works correctly on the **password** field:

![image](https://user-images.githubusercontent.com/20834957/71316712-abfac000-2442-11ea-9b24-70df7f877704.png)

**Comment by varjolintu** [comment]
@kekukui Check the URL added to Site Preferences. It should be `https://www.amazon.com/ap/signin` or similar. IF not, add it manually.

**Comment by trupf** [comment]
Even so this is an old issue report, the sign in on Amazon is still not working. The issue is the same as described above, the url for me is correct: https://www.amazon.de/ap/signin (I guess on .com it is the same issue). Login with autotype works but is not very relyable as the time to switch between username screen and password screen differs depending on cpu usage, browser, operationg system and so on.

**Comment by varjolintu** [comment]
@trupf For me amazon.de works great. Even if username, password and 2FA are on different pages, there are no problems logging in. If you have any settings for the site in Site Preferences settings you can delete them. It should work automatically without any manual adjusting.

**Comment by trupf** [comment]
I had this issue with version 1.7.3. After resetting my site preferences for Amazon, version 1.7.4 seams to work.

**Comment by trupf** [comment]
Although Amazon is working, ebay.de still isn't. I get the user name filled in, but not the password. The password field doesn't even show the keepassxc icon. For a second login (ebay does in this case remember the user name and only asks for the password) the password field gets filled in by keepassxc.

**Comment by varjolintu** [comment]
@trupf There's already issue opened for eBay. It will be fixed for the next version.

**Comment by smekkley** [comment]
Disabling `Use predefined sites for compatibility` fixes the issue with amazon.de and also ebay.

**Comment by varjolintu** [comment]
> Disabling `Use predefined sites for compatibility` fixes the issue with amazon.de and also ebay.

That's.. interesting.
