### ISSUE TITLE
New Credentials Banner Appears on Same Sites When using Existing Credentials and No Change

### ISSUE THREAD

**Issue by agsteele** [keepassxreboot/keepassxc-browser#753]
Show a banner on the page when new credentials can be saved to the database.

## Expected Behavior

On some, but not all, websites when I get the user login credentials from KeePass and successfully login I am presented with a banner which I would expect to see only when something has changed or a new record is required in KeePass.

Because nothing has changed in the username or password I would not expect the banner to appear.

## Steps to Reproduce (for bugs)

1. Go to site where the issue exists - eg: https://esavings.shawbrook.co.uk/BankFast/Shawbrook
2. Use KeePassXC-Browser to insert username and password from KeePass database
3. Click Login 'button' and banner automatically appears

## Debug info

 KeePassXC-Browser Version: 1.5.4
KeePassXC Version: 2.4.3 
Operating system: Windows 10
Browser: Firefox 72.0.1 (64bit)

**Comment by varjolintu** [comment]
This happens because the site uses some JavaScript "security" feature that actually sets the password input field data to asterisks. So, my test entry had a password `test` which would be changed to `****` and the database password is compared to that. That is why the extension thinks the password has been changed.

As a workaround you can add the site to Site Preferences tab in the extension settings and select "Disable new/modified credentials" from the combo box.

**Comment by jt196** [comment]
Came here to say I've had this issue too - I'm not sure this is resolved, just a workaround, no? 

So with this behaviour, the update functionality is broken on these sites. Doing some testing (after using Bitwarden) and I am not experiencing this problem with BW.

**Comment by varjolintu** [comment]
@jt196 What sites are you referring to?

**Comment by jt196** [comment]
Went through a bunch actually and it got so annoying I had to deactivate the plugin and just use the AutoType function (which is awesome btw!). 

Hitrate is much lower than I initially thought (couldn't find any this time round) probably due to some teething issues getting this plugin set up. If I notice this any more I'll report it.

**Comment by varjolintu** [comment]
@jt196 Some of the submit detections are fixed for the next release, so it should be more reliable.
