### ISSUE TITLE
Password save dialogue opens only on second click

### ISSUE THREAD

**Issue by guido4000** [keepassxreboot/keepassxc-browser#80]
## Expected Behavior
When logging into a new site the icons blinks and when clicking on the icon the 'password save' dialogue shows up.

## Current Behavior
When logging into a new site the icons blinks as it should.
When clicking on the icon it show the standard message: "KeePassXC-Browser has been configured using the identifier "db" and is successfully connected to KeePassXC. ".
When clicking a second time on the icon the password save dialogue is shown.

## Possible Solution
Fix the bug to show the save dialogue on first click

## Steps to Reproduce (for bugs)
1. login to any website without saved password credentials

## Debug info

 KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1
Operating system: Ubuntu 17.10
Browser: Firefox 59
Proxy used: YES

**Comment by macau23** [comment]
I am seeing this too. It really kills the "this new shiny is cool" experience.

**Comment by varjolintu** [comment]
I’ll look at this next week. Sorry for the delay and all the silence (with other issues too).

**Comment by varjolintu** [comment]
Cannot reproduce this. With some sites the icon blinks at first, then stops and starts blinking again. With both blinking cases it works when I click the icon. Also, passwords are saved. You could help debugging this by adding the following line to `browserAction.js` after line 202 (the function line):
`console.log('tabId: ' + tabId + ', username: ' + username + ', password: ' + password + ', url: ' + url + ', exists: ' + usernameExists + ', credList: ' + credentialsList);` and then debugging the extension. Needs a bit tuning..

With this you can see if some parameters are missing and the saving doesn't go forward because of that.

**Comment by varjolintu** [comment]
Duplicate issue: https://github.com/keepassxreboot/keepassxc-browser/issues/67.
