### ISSUE TITLE
Google shows 'Forgot email' screen rather than password field

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc-browser#802]
## Expected Behavior
[When logging in to Google (YouTube)](https://accounts.google.com/ServiceLogin/identifier?service=youtube), go to 'Next' (password field) after entering the email address, allowing me to click-to-fill the password.

## Current Behavior
Click-to-fill, KPXC-browser shows the 'Forgot email' field (rather than the password entry field). This renders KPXC-browser useless for logging in to Google.

## Debug info
KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Win32
Browser: Mozilla Firefox 73.0

**Comment by varjolintu** [comment]
Have you enabled Username-only Detection for Google URL's?

**Comment by keunes** [comment]
Hi @varjolintu. Yes I have. Would you have a Google account you could test this with?

Just tried again and also on my home device I'm experiencing this issue:
KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 73.0

**Comment by varjolintu** [comment]
I have no trouble signing in to Youtube. It's the same `accounts.google.com` page that should work nicely. Make sure the URL in the Site Preferences is `https://accounts.google.com/*`.

**Comment by keunes** [comment]
Hi @varjolintu,

Thanks for helping out, and sorry for the late reply. I just finally got to check, and saw that the URL in the entry is `https://accounts.google.com` - so without the asterisk. Trying to replace it with `https://accounts.google.com/*` as you proposed gives an error: `Invalid URL`.

Maybe related: I have two entries for Google (two different accounts). One has `https://accounts.google.com` as URL, the other one `https://google.com`. Both have this same issue (showing 'Forgot email' screen). The issue: on most other websites the extension shows the two options when clicking on the extension icon. This list is shown when there's a red question mark on the icon. However, for Google, these two options aren't shown - only the related intro text:
![image](https://user-images.githubusercontent.com/11229646/83500654-5cbfbd80-a4bf-11ea-86ee-1d62be743831.png)

**Comment by varjolintu** [comment]
@keunes Please note that I wasn't talking about the entry URL but the URL you put to Site Preferences tab in the extension settings.

**Comment by keunes** [comment]
Ah, sorry - I misunderstood that.

I just checked, and the URL you mentioned was indeed listed in the Site Preferences:
![image](https://user-images.githubusercontent.com/11229646/83511455-f5aa0500-a4ce-11ea-8ab5-dc3dd96940af.png)

**Comment by Ouack23** [comment]
I have the exact same problem.
I manually set the login-only detection setting like this (sorry for french language) : 
![image](https://user-images.githubusercontent.com/5161865/93332184-be632800-f821-11ea-92fb-3bcbe7be3477.png)

I am able to enter my email in the login box with keepassxc-browser, but it redirects me to the following form : 
![image](https://user-images.githubusercontent.com/5161865/93332356-04b88700-f822-11ea-9e51-b92f99303ae5.png)

I think the problem is that the browser extension does the following : 
_Detect login field
_Fill login
_Press TAB
_Press ENTER

If the press TAB step was removed it would work I guess. But would it break other websites ? Hard for me to tell, I installed keepassxc 30 minutes ago...

Same thing happen if I disable login only detection, manually type my email in the login form and use the browser extension to input and submit my password : the password is entered correctly, but the extension presses TAB and then enter, which again, does not work in the google form : the password is just printed in clear text instead of being submitted because of the TAB step bringing the focus to the "Show Password" icon in the password field.

A workaround is to modify your KeepassXC Google entry to override the default auto-type sequence with the following one : 
`{USERNAME}{ENTER}{DELAY 1000}{PASSWORD}{ENTER}`
Then just go to the google form, open KeepassXC, select your entry and press CTRL+SHIFT+V or whatever your auto-type shortcut is in the main app. This does not use the browser extension.

If you need more testing, I'm here. I think this is quite urgent as Google / GMail  / Youtube **sadly** are the most visited websites and their login form not working with this extension is a big con to use KeepassXC IMO.

**Comment by varjolintu** [comment]
I'll test the Auto-Submit bug. It might detect a wrong submit from the form.

Sadly Google/GMail/Youtube sites gives the biggest headaches.

**Comment by varjolintu** [comment]
@Ouack23 I'll find a way.

**Comment by varjolintu** [comment]
Fixed. I had to add a special handling for `accounts.google.com`, but this is necessary because it's a popular page. We want to ensure the compatibility of these sites.
